const fs=require('node:fs');const path=require('node:path');const cp=require('node:child_process');
const root=path.resolve(__dirname,'..','..','..'),artifact=name=>JSON.parse(fs.readFileSync(path.join(root,'artifacts','redo','r02',name),'utf8'));
const inventory=fs.readFileSync(path.join(root,'docs','redo','r01','component-state-inventory.md'),'utf8').split(/\r?\n/).filter(x=>/^\| UI-\d{3} \|/.test(x)).map(x=>x.split('|')[1].trim());
const matrix=artifact('component-migration-matrix.json').rows,state=artifact('state-coverage-matrix.json'),catalog=artifact('salesops-component-catalog.json'),parity=artifact('product-parity.json');
const expected=Array.from({length:73},(_,i)=>`UI-${String(i+1).padStart(3,'0')}`),ids=matrix.map(x=>x.ordospaceInventoryId),unique=new Set(ids),fail=[];
const check=(ok,msg)=>{if(!ok)fail.push(msg);};
check(JSON.stringify(inventory)===JSON.stringify(expected),'Round 1 inventory must be UI-001..UI-073');check(matrix.length===73,'matrix row count');check(unique.size===73,'duplicate IDs');check(expected.every(id=>unique.has(id)),'missing IDs');check(ids.every(id=>expected.includes(id)),'additional IDs');
for(const row of matrix){check(['Exact','Adapted','Derived'].includes(row.classification),`${row.ordospaceInventoryId} class`);check(/^Round [3-9]$/.test(row.implementationRound),`${row.ordospaceInventoryId} round`);check(row.salesopsZipEvidence||row.derivedBasis,`${row.ordospaceInventoryId} evidence`);check(row.verificationMethod,`${row.ordospaceInventoryId} verification`);check(row.classification!=='Derived'||/Combine/.test(row.derivedBasis),`${row.ordospaceInventoryId} derived basis`);check(!row.completionStatus.includes('Unresolved'),`${row.ordospaceInventoryId} unresolved`);for(const evidence of row.evidence){if(evidence.startsWith('evidence/')||evidence.startsWith('docs/'))check(fs.existsSync(path.join(root,evidence)),`${row.ordospaceInventoryId} missing evidence ${evidence}`);}}
check(state.rowCount===73&&state.unresolved===0,'state coverage');check(state.rows.every(r=>Object.values(r.states).every(v=>v!=='Unresolved')),'unresolved states');check(catalog.components.every(x=>x.zipFile&&x.symbol&&x.liveStatus),'catalog fields');check(parity.productParity,'product parity');
const csvLines=fs.readFileSync(path.join(root,'artifacts','redo','r02','component-migration-matrix.csv'),'utf8').trim().split(/\r?\n/);check(csvLines.length===74,'CSV rows');const mdRows=fs.readFileSync(path.join(root,'docs','redo','r02','component-migration-matrix.md'),'utf8').split(/\r?\n/).filter(x=>/^\| UI-\d{3} \|/.test(x));check(mdRows.length===73,'Markdown rows');
const required=['README.md','salesops-source-audit.md','salesops-live-audit.md','salesops-token-spec.md','salesops-component-catalog.md','component-migration-matrix.md','state-coverage-matrix.md','migration-architecture-decisions.md','round-allocation-plan.md','product-parity.md','verification-results.md'];for(const f of required)check(fs.existsSync(path.join(root,'docs','redo','r02',f)),`missing doc ${f}`);
const productStatus=cp.execFileSync('git',['status','--porcelain=v1','--untracked-files=all'],{cwd:root,encoding:'utf8'}).trim().split(/\r?\n/).filter(Boolean).map(x=>x.slice(3).replaceAll('\\','/')).filter(x=>!/^(docs\/redo\/r02\/|artifacts\/redo\/r02\/|evidence\/redo\/r02\/|tests\/redo\/r02\/|references\/prompts\/round-2\.md$)/.test(x));check(productStatus.length===0,`disallowed working changes: ${productStatus.join(',')}`);
if(fail.length){console.error(JSON.stringify({ok:false,fail},null,2));process.exit(1);}console.log(JSON.stringify({ok:true,inventory:73,matrix:73,unique:73,catalog:catalog.count,stateRows:73,unresolved:0,csvRows:73,markdownRows:73,productParity:true}));
