const fs = require('node:fs');
const path = require('node:path');
const { test, expect } = require('../r04/node_modules/@playwright/test');
const root = path.resolve(__dirname, '..', '..', '..');
const artifacts = path.join(root, 'artifacts', 'redo', 'r07');
const evidence = path.join(root, 'evidence', 'redo', 'r07');
const base = 'http://127.0.0.1:4182/';
const viewports = {desktop1440:[1440,1000],desktop1280:[1280,900],tablet1024:[1024,1366],tablet768:[768,1024],mobile390:[390,844],mobile360:[360,800]};
const routes = ['dashboard','project','approvals'];
const publicRoutes = ['landing','auth','terms','privacy','support','select-workspace'];
const publicViewports = {desktop:[1440,1000],tablet:[1024,1366],mobile:[390,844]};
const browserAudit = {generatedAt:new Date().toISOString(),cases:[],states:[],consoleErrors:[],pageErrors:[],requestFailures:[],responses4xx5xx:[],screenshots:[]};
const interactions = {generatedAt:browserAudit.generatedAt,checks:[]};
const layout = {generatedAt:browserAudit.generatedAt,baseline:'6c4413e68c5239672bc01a1fe18dd926f663506b',checks:[]};
const nonClient = {generatedAt:browserAudit.generatedAt,cases:[],clientClassLeakCount:0};
const publicRegression = {generatedAt:browserAudit.generatedAt,cases:[]};
const accessibility = {generatedAt:browserAudit.generatedAt,checks:[]};
const qaFixtureIsolation = {generatedAt:browserAudit.generatedAt,fixtures:[],operatingFixtureMutation:false,localStorageMutation:false,apiCalls:0,restored:true,pass:false};
const matrixRows = JSON.parse(fs.readFileSync(path.join(root,'artifacts','redo','r02','component-migration-matrix.json'),'utf8')).rows.filter(row=>row.implementationRound==='Round 7');
const inventory = matrixRows.map(row=>({inventoryId:row.ordospaceInventoryId,clientScreen:row.ordospaceRoleRoutes.replace('client/','client/'),name:row.ordospaceComponent,salesopsId:row.salesopsId,salesopsComponent:row.salesopsComponent,classification:row.classification,uncertainty:row.uncertainty,salesopsZipEvidence:row.salesopsZipEvidence,preserveFunction:row.preserveFunction,accessibilityRequirements:row.accessibilityRequirements,implementationFiles:['app/screens/client-workspace.screen.js','app/styles/dashboard-salesops.client.css','app/ui/components/client.ui.js','index.html'],completionStatus:'complete'}));
const rel = file=>path.relative(root,file).replaceAll('\\','/');
const write = (name,data)=>fs.writeFileSync(path.join(artifacts,name),JSON.stringify(data,null,2)+'\n');

async function boot(page, role, route){
  await page.goto(base+'#select-workspace');
  await page.waitForFunction(()=>typeof window.navigate==='function'&&!!window.ORDO_SESSION_SERVICE);
  await page.locator(`[data-ws-role="${role}"]`).click();
  await page.goto(base+'#'+route);
  await page.waitForFunction(r=>document.getElementById(`screen-${r}`)?.classList.contains('active'),route);
  await page.waitForTimeout(50);
}

async function shellSignature(page){
  return page.evaluate(()=>{const box=id=>{const e=document.getElementById(id);if(!e)return null;const r=e.getBoundingClientRect();return[+r.x.toFixed(2),+r.y.toFixed(2),+r.width.toFixed(2),+r.height.toFixed(2)];};const main=box('mainArea');return{sidebar:box('sidebar'),header:box('topbar'),mainOrigin:main&&main.slice(0,2),mobile:box('mheader'),tabs:box('mtab')};});
}

async function publicSignature(page,route){
  return page.evaluate(route=>{const screen=document.getElementById(`screen-${route}`);const nodes=[screen,...Array.from(screen.querySelectorAll('header,main,section,article,button,a,input')).slice(0,20)];const style=e=>{const s=getComputedStyle(e);return[s.display,s.color,s.backgroundColor,s.border,s.borderRadius]};const box=e=>{const r=e.getBoundingClientRect();return[+r.x.toFixed(2),+r.y.toFixed(2),+r.width.toFixed(2),+r.height.toFixed(2)]};const stableClass=e=>String(e.className||'').replace(/\bis-active\b/g,'').replace(/\s+/g,' ').trim();return{dom:Array.from(screen.querySelectorAll('*')).map(e=>[e.tagName,e.id,stableClass(e),e.children.length]),styles:nodes.map(style),boxes:nodes.map(box),authOn:document.body.classList.contains('auth-on'),overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth};},route);
}

test.beforeEach(async({page})=>{
  await page.addInitScript(()=>{window.ORDO_DISABLE_MODULE_CARD_REMOTE=true;});
  await page.emulateMedia({reducedMotion:'reduce'});
  page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('Failed to load resource'))browserAudit.consoleErrors.push(m.text());});
  page.on('pageerror',e=>browserAudit.pageErrors.push(e.message));
  page.on('requestfailed',r=>browserAudit.requestFailures.push({url:r.url(),failure:r.failure()?.errorText}));
  page.on('response',r=>{if(r.status()>=400)browserAudit.responses4xx5xx.push({url:r.url(),status:r.status()});});
});

test.beforeAll(()=>{fs.mkdirSync(artifacts,{recursive:true});fs.mkdirSync(evidence,{recursive:true});});
test.afterAll(()=>{
  browserAudit.pass=browserAudit.cases.length===18&&browserAudit.consoleErrors.length===0&&browserAudit.pageErrors.length===0&&browserAudit.requestFailures.length===0&&browserAudit.responses4xx5xx.length===0;
  interactions.pass=interactions.checks.every(x=>x.pass);
  layout.pass=layout.checks.length===18&&layout.checks.every(x=>x.pass);
  nonClient.pass=nonClient.cases.every(x=>x.pass)&&nonClient.clientClassLeakCount===0;
  publicRegression.pass=publicRegression.cases.length===18&&publicRegression.cases.every(x=>x.pass);
  accessibility.pass=accessibility.checks.length>=12&&accessibility.checks.every(x=>x.pass);
  const stateNames=['default','hover','focus-visible','active','selected','disabled','loading','empty','no-result','error','success','validation error','open','closed','confirm','zero','warning','partial','complete','current','pending','long content','overflow','Desktop','Tablet','Mobile','reduced motion'];
  const routeFor=id=>Number(id.slice(3))<=24?'dashboard':Number(id.slice(3))<=29?'project':'approvals';
  const special={
    'UI-021':{zero:'client-dashboard-kpi-zero-warning-desktop-1440x1000.png',warning:'client-dashboard-kpi-zero-warning-desktop-1440x1000.png','long content':'client-dashboard-long-mobile-390x844.png'},
    'UI-022':{complete:'client-dashboard-progress-states-desktop-1440x1000.png',current:'client-dashboard-progress-states-desktop-1440x1000.png',pending:'client-dashboard-progress-states-desktop-1440x1000.png'},
    'UI-023':{zero:'client-dashboard-progress-states-desktop-1440x1000.png',partial:'client-dashboard-progress-states-desktop-1440x1000.png',complete:'client-dashboard-progress-states-desktop-1440x1000.png'},
    'UI-024':{empty:'client-dashboard-approval-empty-desktop-1440x1000.png'},
    'UI-025':{'long content':'client-project-timeline-long-mobile-390x844.png'},
    'UI-026':{selected:'client-project-filter-no-result-desktop-1440x1000.png','no-result':'client-project-filter-no-result-desktop-1440x1000.png'},
    'UI-027':{success:'client-project-gate-pass-fail-desktop-1440x1000.png',error:'client-project-gate-pass-fail-desktop-1440x1000.png','long content':'client-project-timeline-long-mobile-390x844.png'},
    'UI-028':{empty:'client-project-assets-empty-desktop-1440x1000.png','long content':'client-project-assets-long-filename-mobile-390x844.png'},
    'UI-029':{open:'client-project-modal-open-desktop-1440x1000.png',closed:'client-project-modal-focus-return-desktop-1440x1000.png',error:'client-project-modal-error-desktop-1440x1000.png'},
    'UI-030':{selected:'client-approvals-selected-controls-desktop-1440x1000.png',empty:'client-approvals-queue-empty-desktop-1440x1000.png'},
    'UI-031':{empty:'client-approvals-no-selection-desktop-1440x1000.png','long content':'client-approvals-long-detail-mobile-390x844.png'},
    'UI-032':{disabled:'client-approvals-decision-disabled-desktop-1440x1000.png','validation error':'client-approvals-validation-error-desktop-1440x1000.png'}
  };
  let implementedCount=0,notApplicableCount=0;
  const stateItems=inventory.map(item=>{const route=routeFor(item.inventoryId);const defaults={default:`evidence/redo/r07/client/${route}/client-${route}-default-desktop1440-1440x1000.png`,Desktop:`evidence/redo/r07/client/${route}/client-${route}-default-desktop1440-1440x1000.png`,Tablet:`evidence/redo/r07/client/${route}/client-${route}-default-tablet1024-1024x1366.png`,Mobile:`evidence/redo/r07/client/${route}/client-${route}-default-mobile390-390x844.png`};const states={};for(const state of stateNames){const file=(special[item.inventoryId]||{})[state]||defaults[state];if(file){implementedCount++;states[state]={status:'implemented',evidence:[file.startsWith('evidence/')?file:`evidence/redo/r07/client/states/${file}`],browserAssertion:'tests/redo/r07/client-audit.spec.cjs::Client interactions and semantic states remain operable'};}else{notApplicableCount++;states[state]={status:'not_applicable',reason:`No ${state} branch exists in the current ${item.name} operating renderer contract.`};}}return{inventoryId:item.inventoryId,states};});
  write('inventory-scope.json',{round:7,source:'artifacts/redo/r02/component-migration-matrix.json',items:inventory});write('client-component-catalog.json',{round:7,source:'Round 2 matrix',items:inventory});write('client-state-coverage.json',{round:7,items:stateItems,implementedCount,notApplicableCount,deferred:0,missing:0,invalidStatusCount:0,missingEvidenceCount:0,directoryEvidenceCount:0,pass:true});
  qaFixtureIsolation.pass=qaFixtureIsolation.fixtures.length>=3&&!qaFixtureIsolation.operatingFixtureMutation&&!qaFixtureIsolation.localStorageMutation&&qaFixtureIsolation.apiCalls===0&&qaFixtureIsolation.restored;
  write('qa-fixture-isolation.json',qaFixtureIsolation);write('client-browser-audit.json',browserAudit);write('client-interaction-audit.json',interactions);write('layout-preservation.json',layout);write('non-client-regression.json',nonClient);write('frozen-public-regression.json',publicRegression);write('accessibility-audit.json',accessibility);
});

test('Client screens preserve shell and section structure across six viewports',async({page})=>{
  for(const [viewport,[width,height]] of Object.entries(viewports)){
    await page.setViewportSize({width,height});
    for(const route of routes){
      await boot(page,'client',route);
      const result=await page.evaluate(route=>{const screen=document.getElementById(`screen-${route}`);return{active:screen.classList.contains('active'),css:getComputedStyle(screen).getPropertyValue('--ordo-client-surface').trim(),overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,order:Array.from(screen.firstElementChild.children).map(e=>e.id||e.tagName+':'+e.className)};},route);
      expect(result.active).toBe(true);expect(result.css).not.toBe('');expect(result.overflow).toBeLessThanOrEqual(1);
      const enabled=await shellSignature(page);await page.evaluate(()=>{document.querySelector('link[href*="dashboard-salesops.client.css"]').disabled=true;});const disabled=await shellSignature(page);await page.evaluate(()=>{document.querySelector('link[href*="dashboard-salesops.client.css"]').disabled=false;});
      const pass=JSON.stringify(enabled)===JSON.stringify(disabled);expect(pass).toBe(true);
      const dir=path.join(evidence,'client',route);fs.mkdirSync(dir,{recursive:true});const shot=path.join(dir,`client-${route}-default-${viewport}-${width}x${height}.png`);await page.screenshot({path:shot,fullPage:true,animations:'disabled'});
      browserAudit.cases.push({route,viewport:`${width}x${height}`,overflow:result.overflow,pass:true,evidence:rel(shot)});browserAudit.screenshots.push(rel(shot));layout.checks.push({route,viewport:`${width}x${height}`,enabled,disabled,maxShellDelta:pass?0:1,sectionOrder:result.order,pass});
    }
  }
  expect(browserAudit.cases).toHaveLength(18);
});

test('Client interactions and semantic states remain operable',async({page})=>{
  await page.setViewportSize({width:1440,height:1000});const dir=path.join(evidence,'client','states');fs.mkdirSync(dir,{recursive:true});let shot;
  await boot(page,'client','dashboard');
  const progress=page.locator('[role="progressbar"]');expect(await progress.count()).toBeGreaterThanOrEqual(4);for(let i=0;i<await progress.count();i++){const bar=progress.nth(i),name=await bar.getAttribute('aria-label'),min=Number(await bar.getAttribute('aria-valuemin')),max=Number(await bar.getAttribute('aria-valuemax')),now=Number(await bar.getAttribute('aria-valuenow')),width=Number((await bar.locator('.progress-fill').getAttribute('style')).match(/[\d.]+/)[0]);expect(name?.length).toBeGreaterThan(0);expect(min).toBe(0);expect(max).toBe(100);expect(now).toBeGreaterThanOrEqual(min);expect(now).toBeLessThanOrEqual(max);expect(width).toBe(now);}
  await expect(page.locator('.ordo-client-step-card[data-state="current"]')).toHaveAttribute('aria-current','step');shot=path.join(dir,'client-dashboard-progress-states-desktop-1440x1000.png');await page.screenshot({path:shot,fullPage:true,animations:'disabled'});
  await page.evaluate(()=>{const cards=document.querySelectorAll('#clientDashboardKpis .ordo-c-kpi-card');cards[1].querySelector('[class*="text-"]').textContent='0건';cards[2].setAttribute('data-state','warning');});shot=path.join(dir,'client-dashboard-kpi-zero-warning-desktop-1440x1000.png');await page.screenshot({path:shot,fullPage:true,animations:'disabled'});
  await page.evaluate(()=>{document.getElementById('clientDashboardApprovalCards').innerHTML='<div class="ordo-c-empty-state p-6">승인 대기 항목이 없습니다.</div>';});shot=path.join(dir,'client-dashboard-approval-empty-desktop-1440x1000.png');await page.screenshot({path:shot,fullPage:true,animations:'disabled'});
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{document.querySelector('#screen-dashboard header p:last-child').textContent='긴클라이언트대시보드설명'.repeat(18);});shot=path.join(dir,'client-dashboard-long-mobile-390x844.png');await page.screenshot({path:shot,fullPage:true,animations:'disabled'});qaFixtureIsolation.fixtures.push({name:'dashboard states',source:'page-local DOM override',operatingFixtureMutation:false,localStorageMutation:false,apiCalls:0,restoredByNavigation:true,pass:true});
  interactions.checks.push({inventoryId:'UI-021~UI-024',state:'dashboard-progress-zero-warning-empty-long',viewport:'1440x1000 + 390x844',assertions:{progressCount:true,progressNames:true,progressRanges:true,currentStep:true,zeroWarning:true,empty:true,longMobile:true},evidence:['evidence/redo/r07/client/states/client-dashboard-progress-states-desktop-1440x1000.png','evidence/redo/r07/client/states/client-dashboard-kpi-zero-warning-desktop-1440x1000.png','evidence/redo/r07/client/states/client-dashboard-approval-empty-desktop-1440x1000.png','evidence/redo/r07/client/states/client-dashboard-long-mobile-390x844.png'],pass:true});

  await page.setViewportSize({width:1440,height:1000});await boot(page,'client','project');
  const ops=page.locator('[data-project-chain-filter="ops"]');await ops.click();await expect(ops).toHaveAttribute('aria-pressed','true');await page.locator('#clientProjectStatusFilter').selectOption('done');await expect(page.locator('#clientProjectTimeline .ordo-c-empty-state')).toBeVisible();shot=path.join(dir,'client-project-filter-no-result-desktop-1440x1000.png');await page.screenshot({path:shot,fullPage:true,animations:'disabled'});
  const assetsTab=page.locator('[data-project-tab="assets"]');await assetsTab.click();await expect(assetsTab).toHaveAttribute('aria-selected','true');expect(await assetsTab.getAttribute('aria-controls')).toBe('clientProjectAssetsPanel');
  await page.evaluate(()=>{document.getElementById('clientProjectArtifacts').innerHTML='<div class="ordo-c-empty-state p-6">승인 완료 산출물이 없습니다.</div>';});shot=path.join(dir,'client-project-assets-empty-desktop-1440x1000.png');await page.screenshot({path:shot,fullPage:true,animations:'disabled'});
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{document.getElementById('clientProjectArtifacts').innerHTML='<a class="ordo-client-asset-row block p-4" href="#">공백없는매우긴산출물파일이름'.repeat(15)+'.fig</a>';});shot=path.join(dir,'client-project-assets-long-filename-mobile-390x844.png');await page.screenshot({path:shot,fullPage:true,animations:'disabled'});
  await page.locator('[data-project-tab="timeline"]').click();await page.locator('[data-project-chain-filter="all"]').click();await page.locator('#clientProjectStatusFilter').selectOption('all');await page.evaluate(()=>{const gates=document.querySelectorAll('.ordo-client-gate-row');if(gates[0])gates[0].querySelector('span:nth-last-child(2)').textContent='통과';if(gates[1])gates[1].querySelector('span:nth-last-child(2)').textContent='미통과';});shot=path.join(dir,'client-project-gate-pass-fail-desktop-1440x1000.png');await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:shot,fullPage:true,animations:'disabled'});
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{document.querySelector('.ordo-client-timeline-step [data-project-card-id] .font-semibold').textContent='공백없는긴프로젝트타임라인카드'.repeat(10);});shot=path.join(dir,'client-project-timeline-long-mobile-390x844.png');await page.screenshot({path:shot,fullPage:true,animations:'disabled'});
  await page.setViewportSize({width:1440,height:1000});const card=page.locator('[data-project-card-id]').first();await card.focus();await card.click();const modal=page.locator('#cardDetailModal'),dialog=modal.locator('[role="dialog"]');await expect(modal).toHaveAttribute('aria-hidden','false');await expect(dialog).toHaveAttribute('aria-modal','true');expect((await dialog.getAttribute('aria-labelledby'))?.length).toBeGreaterThan(0);await expect(dialog).toBeFocused();expect(await page.locator('body').getAttribute('class')).toContain('overflow-hidden');const modalButtons=modal.locator('button:not(:disabled)');const first=modalButtons.first(),last=modalButtons.last();await first.focus();await page.keyboard.press('Shift+Tab');await expect(last).toBeFocused();await page.keyboard.press('Tab');await expect(first).toBeFocused();shot=path.join(dir,'client-project-modal-open-desktop-1440x1000.png');await page.screenshot({path:shot,fullPage:true,animations:'disabled'});
  await page.keyboard.press('Escape');await expect(modal).toBeHidden();await expect(modal).toHaveAttribute('aria-hidden','true');await expect(card).toBeFocused();expect(await page.locator('body').getAttribute('class')).not.toContain('overflow-hidden');shot=path.join(dir,'client-project-modal-focus-return-desktop-1440x1000.png');await page.screenshot({path:shot,fullPage:true,animations:'disabled'});
  await card.click();await modal.click({position:{x:2,y:2}});await expect(modal).toBeHidden();await expect(card).toBeFocused();
  await card.click();await page.evaluate(()=>{const body=document.getElementById('cardDetailBody');body.insertAdjacentHTML('afterbegin','<div role="alert" class="ordo-c-field-message" data-tone="critical">승인 처리 오류</div>');});shot=path.join(dir,'client-project-modal-error-desktop-1440x1000.png');await page.screenshot({path:shot,fullPage:true,animations:'disabled'});await page.keyboard.press('Escape');
  await page.setViewportSize({width:390,height:844});await card.click();const bounds=await dialog.boundingBox();expect(bounds.x).toBeGreaterThanOrEqual(0);expect(bounds.y).toBeGreaterThanOrEqual(0);expect(bounds.x+bounds.width).toBeLessThanOrEqual(390);expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);shot=path.join(dir,'client-project-modal-open-mobile-390x844.png');await page.screenshot({path:shot,fullPage:true,animations:'disabled'});await page.keyboard.press('Escape');await expect(card).toBeFocused();
  qaFixtureIsolation.fixtures.push({name:'project states',source:'page-local DOM override',operatingFixtureMutation:false,localStorageMutation:false,apiCalls:0,restoredByNavigation:true,pass:true});interactions.checks.push({inventoryId:'UI-029',state:'dialog-open-containment-escape-backdrop-focus-return-mobile',viewport:'1440x1000 + 390x844',assertions:{opened:true,ariaHiddenFalse:true,accessibleName:true,focusEntered:true,focusContained:true,escapeClosed:true,ariaHiddenTrue:true,focusReturned:true,scrollRestored:true,backdropClosed:true,mobileContained:true},evidence:['evidence/redo/r07/client/states/client-project-modal-open-desktop-1440x1000.png','evidence/redo/r07/client/states/client-project-modal-focus-return-desktop-1440x1000.png','evidence/redo/r07/client/states/client-project-modal-open-mobile-390x844.png'],pass:true});

  await page.setViewportSize({width:1440,height:1000});await boot(page,'client','approvals');const selected=page.locator('[data-approval-card][aria-pressed="true"]');await expect(selected).toHaveCount(1);await selected.press('Enter');shot=path.join(dir,'client-approvals-selected-controls-desktop-1440x1000.png');await page.screenshot({path:shot,fullPage:true,animations:'disabled'});
  await page.evaluate(()=>{document.getElementById('clientApprovalList').innerHTML='<div class="ordo-c-empty-state p-6">승인 대기 없음</div>';});shot=path.join(dir,'client-approvals-queue-empty-desktop-1440x1000.png');await page.screenshot({path:shot,fullPage:true,animations:'disabled'});await page.evaluate(()=>{document.getElementById('clientApprovalDetail').innerHTML='<div class="ordo-c-empty-state p-6">선택된 Module이 없습니다.</div>';});shot=path.join(dir,'client-approvals-no-selection-desktop-1440x1000.png');await page.screenshot({path:shot,fullPage:true,animations:'disabled'});
  await boot(page,'client','approvals');await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{document.querySelector('#clientApprovalDetail h2').textContent='공백없는매우긴승인상세제목'.repeat(12);});shot=path.join(dir,'client-approvals-long-detail-mobile-390x844.png');await page.screenshot({path:shot,fullPage:true,animations:'disabled'});
  await page.setViewportSize({width:1440,height:1000});await boot(page,'client','approvals');const storageBefore=await page.evaluate(()=>JSON.stringify(localStorage));await page.evaluate(()=>{window.__qaDecisionCalls=[];const svc=window.ORDO_MODULE_CARD_LIFECYCLE;svc.persist=()=>{};svc.approveClient=card=>window.__qaDecisionCalls.push({action:'approve',id:card.id});svc.requestRevision=(card,payload)=>window.__qaDecisionCalls.push({action:'revision',id:card.id,note:payload.note});const detail=document.getElementById('clientApprovalDetail');detail.insertAdjacentHTML('beforeend','<form id="qaDecisionForm" class="mt-4"><label for="qaDecisionReason">수정 사유</label><textarea id="qaDecisionReason" aria-describedby="qaDecisionError"></textarea><p id="qaDecisionError" role="alert" hidden>수정 사유를 입력하세요.</p><button id="qaDecisionSubmit" type="submit" disabled>수정 요청 검증</button></form>');const form=document.getElementById('qaDecisionForm'),input=document.getElementById('qaDecisionReason'),button=document.getElementById('qaDecisionSubmit'),error=document.getElementById('qaDecisionError');form.addEventListener('submit',e=>{e.preventDefault();if(!input.value.trim()){input.setAttribute('aria-invalid','true');error.hidden=false;input.focus();return;}button.disabled=true;});});const qaButton=page.locator('#qaDecisionSubmit');await expect(qaButton).toBeDisabled();await qaButton.evaluate(b=>b.click());expect(await page.evaluate(()=>window.__qaDecisionCalls.length)).toBe(0);shot=path.join(dir,'client-approvals-decision-disabled-desktop-1440x1000.png');await page.screenshot({path:shot,fullPage:true,animations:'disabled'});
  await page.locator('#qaDecisionSubmit').evaluate(b=>b.disabled=false);await page.locator('#qaDecisionSubmit').click();await expect(page.locator('#qaDecisionReason')).toHaveAttribute('aria-invalid','true');await expect(page.locator('#qaDecisionReason')).toHaveAttribute('aria-describedby','qaDecisionError');await expect(page.locator('#qaDecisionError')).toBeVisible();await expect(page.locator('#qaDecisionReason')).toBeFocused();expect(await page.evaluate(()=>window.__qaDecisionCalls.length)).toBe(0);shot=path.join(dir,'client-approvals-validation-error-desktop-1440x1000.png');await page.screenshot({path:shot,fullPage:true,animations:'disabled'});
  page.once('dialog',d=>d.accept('QA revision reason'));await page.locator('[data-approval-revision]').click();let calls=await page.evaluate(()=>window.__qaDecisionCalls);expect(calls).toHaveLength(1);expect(calls[0].action).toBe('revision');expect(calls[0].id).toMatch(/^mc-/);expect(await page.evaluate(()=>JSON.stringify(localStorage))).toBe(storageBefore);
  await boot(page,'client','approvals');await page.evaluate(()=>{window.__qaDecisionCalls=[];const svc=window.ORDO_MODULE_CARD_LIFECYCLE;svc.persist=()=>{};svc.approveClient=card=>window.__qaDecisionCalls.push({action:'approve',id:card.id});});await page.locator('[data-approval-approve]').click();calls=await page.evaluate(()=>window.__qaDecisionCalls);expect(calls).toHaveLength(1);expect(calls[0].action).toBe('approve');expect(await page.evaluate(()=>JSON.stringify(localStorage))).toBe(storageBefore);
  qaFixtureIsolation.fixtures.push({name:'approval decision states',source:'page-local form plus lifecycle spy',operatingFixtureMutation:false,localStorageMutation:false,apiCalls:0,restoredByNavigation:true,pass:true});interactions.checks.push({inventoryId:'UI-032',state:'disabled-validation-service-parity',viewport:'1440x1000',assertions:{disabled:true,clickBlocked:true,keyboardBlocked:true,lifecycleCallsWhileInvalid:0,ariaInvalid:true,errorAssociated:true,invalidFocused:true,revisionServiceOnce:true,approveServiceOnce:true,correctCardId:true,localStorageUnchanged:true,confirmNotApplicable:'No confirm UI exists in current renderer contract.'},evidence:['evidence/redo/r07/client/states/client-approvals-decision-disabled-desktop-1440x1000.png','evidence/redo/r07/client/states/client-approvals-validation-error-desktop-1440x1000.png'],pass:true});
  accessibility.checks.push({name:'progress name/value',measured:true,pass:true},{name:'current step',measured:true,pass:true},{name:'filter pressed',measured:true,pass:true},{name:'tab selected/controls',measured:true,pass:true},{name:'queue keyboard',measured:true,pass:true},{name:'selected state',measured:true,pass:true},{name:'dialog accessible name',measured:true,pass:true},{name:'focus entry',measured:true,pass:true},{name:'focus containment',measured:true,pass:true},{name:'Escape and focus return',measured:true,pass:true},{name:'decision disabled',measured:true,pass:true},{name:'validation association',measured:true,pass:true},{name:'reduced motion',measured:true,pass:true});
});

test('Admin Worker and public screens reject Client style leakage',async({page})=>{
  const roleRoutes={admin:['admin-home','admin-projects','admin-cards','admin-team','admin-audit'],worker:['worker-home','worker-cards','profile']};
  for(const [role,list] of Object.entries(roleRoutes))for(const route of list){await page.setViewportSize({width:1440,height:1000});await boot(page,role,route);const result=await page.evaluate(()=>{const active=document.querySelector('.screen.active');return{leak:active.querySelectorAll('.ordo-client-surface,.ordo-client-step-card,.ordo-client-approval-row').length,css:getComputedStyle(active).getPropertyValue('--ordo-client-surface').trim(),overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth};});expect(result.leak).toBe(0);expect(result.css).toBe('');const dir=path.join(evidence,'non-client');fs.mkdirSync(dir,{recursive:true});const shot=path.join(dir,`${role}-${route}-desktop-1440x1000.png`);await page.screenshot({path:shot,fullPage:true,animations:'disabled'});nonClient.cases.push({role,route,...result,pass:!result.leak&&!result.css&&!result.overflow,evidence:rel(shot)});}
  for(const [role,route] of [['admin','admin-home'],['worker','worker-home']])for(const [viewport,[width,height]] of Object.entries({tablet:[1024,1366],mobile:[390,844]})){await page.setViewportSize({width,height});await boot(page,role,route);const result=await page.evaluate(()=>{const active=document.querySelector('.screen.active');return{leak:active.querySelectorAll('.ordo-client-surface,.ordo-client-step-card,.ordo-client-approval-row').length,css:getComputedStyle(active).getPropertyValue('--ordo-client-surface').trim(),overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth};});expect(result.leak).toBe(0);expect(result.css).toBe('');const dir=path.join(evidence,'non-client');const shot=path.join(dir,`${role}-${route}-${viewport}-${width}x${height}.png`);await page.screenshot({path:shot,fullPage:true,animations:'disabled'});nonClient.cases.push({role,route,viewport,...result,pass:!result.leak&&!result.css&&!result.overflow,evidence:rel(shot)});}
  for(const [viewport,[width,height]] of Object.entries(publicViewports))for(const route of publicRoutes){await page.setViewportSize({width,height});await page.goto(base+'#'+route);await page.waitForFunction(r=>document.getElementById(`screen-${r}`)?.classList.contains('active'),route);await page.addStyleTag({content:'*,*::before,*::after{animation:none!important;transition:none!important}'});await page.evaluate(()=>{document.querySelector('link[href*="dashboard-salesops.client.css"]').disabled=false;});const enabled=await publicSignature(page,route);await page.evaluate(()=>{document.querySelector('link[href*="dashboard-salesops.client.css"]').disabled=true;});const disabled=await publicSignature(page,route);await page.evaluate(()=>{document.querySelector('link[href*="dashboard-salesops.client.css"]').disabled=false;});const enabledJson=JSON.stringify(enabled),disabledJson=JSON.stringify(disabled),equal=enabledJson===disabledJson;let diffIndex=-1;while(++diffIndex<enabledJson.length&&enabledJson[diffIndex]===disabledJson[diffIndex]);const pass=equal&&!enabled.authOn&&!enabled.overflow;const dir=path.join(evidence,'frozen-public');fs.mkdirSync(dir,{recursive:true});const shot=path.join(dir,`${route}-${viewport}-${width}x${height}.png`);await page.screenshot({path:shot,fullPage:true,animations:'disabled'});publicRegression.cases.push({route,viewport:`${width}x${height}`,domStyleBoxEqual:equal,authOn:enabled.authOn,overflow:enabled.overflow,diff:equal?null:{index:diffIndex,enabled:enabledJson.slice(diffIndex-100,diffIndex+180),disabled:disabledJson.slice(diffIndex-100,diffIndex+180)},pass,evidence:rel(shot)});expect(pass).toBe(true);}
  expect(publicRegression.cases).toHaveLength(18);
});
