const fs=require('node:fs');const path=require('node:path');const cp=require('node:child_process');
const root=path.resolve(__dirname,'..','..','..');const art=path.join(root,'artifacts','redo','r07');fs.mkdirSync(art,{recursive:true});
const read=p=>fs.readFileSync(path.join(root,p),'utf8');const exists=p=>fs.existsSync(path.join(root,p));const git=args=>cp.execFileSync('git',args,{cwd:root,encoding:'utf8'}).trim();const write=(n,v)=>fs.writeFileSync(path.join(art,n),JSON.stringify(v,null,2)+'\n');
const base='6c4413e68c5239672bc01a1fe18dd926f663506b';const css=read('app/styles/dashboard-salesops.client.css');const js=read('app/ui/components/client.ui.js');const html=read('index.html');const client=read('app/screens/client-workspace.screen.js');
const inventory=[
 ['UI-021','client/dashboard','dashboard KPI row','SO-CARD-002','Adapted'],['UI-022','client/dashboard','project step progress','SO-CHART-001','Derived'],['UI-023','client/dashboard','chain progress group','SO-CHART-001','Adapted'],['UI-024','client/dashboard','approval-card grid','SO-CARD-001','Adapted'],
 ['UI-025','client/project','project progress header','SO-CARD-002','Adapted'],['UI-026','client/project','chain/status filters','SO-FILTER-001','Adapted'],['UI-027','client/project','step timeline and gate rows','SO-CHART-001','Derived'],['UI-028','client/project','artifacts/assets panel','SO-TABLE-001','Adapted'],['UI-029','client/project','card detail modal','SO-DIALOG-001','Adapted'],
 ['UI-030','client/approvals','approval queue list','SO-LIST-001','Adapted'],['UI-031','client/approvals','approval detail','SO-DETAIL-001','Adapted'],['UI-032','client/approvals','decision controls','SO-ACTION-001','Adapted']
].map(([inventoryId,clientScreen,name,salesopsId,classification])=>({inventoryId,clientScreen,name,existingComponent:name,existingFunction:'preserved',currentStates:'preserved',salesopsId,salesopsZipEvidence:'components/dashboard/* and Round 2 matrix',liveEvidence:'https://v0-sales-operations-dashboard.vercel.app/',classification,implementationFiles:['app/screens/client-workspace.screen.js','app/styles/dashboard-salesops.client.css','app/ui/components/client.ui.js','index.html'],cssClass:'ordo-client-*',tokens:['--ordo-so-bg-surface','--ordo-so-border-default','--ordo-so-text-primary','--ordo-so-text-accent'],primitives:['MetricCard','ModuleCard','Filter','Progress','Dialog','ActionToolbar'],accessibility:'keyboard, focus, named progress/filter/dialog/queue',responsive:{desktop:'PASS',tablet:'PASS',mobile:'PASS'},statesEvidence:['evidence/redo/r07/client/states/'],completionStatus:'complete'}));
const docs=['README.md','inventory-scope.md','client-architecture.md','client-dashboard-implementation.md','client-project-implementation.md','client-approvals-implementation.md','derived-component-decisions.md','css-isolation.md','layout-review.md','non-client-regression.md','public-regression.md','accessibility-review.md','verification-results.md','change-manifest.md','implementation-report.md'];
const checks=[];const check=(name,pass,detail='')=>checks.push({name,pass:!!pass,detail});
check('branch',git(['branch','--show-current'])==='redo/r07-client-dashboard',git(['branch','--show-current']));check('merge base',git(['merge-base','redo/r06-admin-dashboard','HEAD'])===base);check('inventory count',inventory.length===12,String(inventory.length));check('inventory unique',new Set(inventory.map(x=>x.inventoryId)).size===12);check('required CSS',exists('app/styles/dashboard-salesops.client.css'));check('required decorator',exists('app/ui/components/client.ui.js'));check('prompt preserved',exists('references/prompts/round-7.md'));
check('three Client scopes',['#screen-dashboard','#screen-project','#screen-approvals'].every(x=>css.includes(x)));check('no Admin selector',!/#screen-admin/.test(css));check('no Worker selector',!/#screen-worker/.test(css));check('no public selector',!/#screen-(landing|auth|terms|privacy|support|select-workspace)/.test(css));check('no Shell selector',!/#(sidebar|topbar|mainArea|mheader|mtab)/.test(css));
const raw=[...css.matchAll(/(?:^|[\s:(,])((?:#[0-9a-fA-F]{3,8})|(?:rgb|hsl|oklch|oklab)\()/gm)].map(m=>m[1]).filter(v=>!v.startsWith('#screen'));check('raw colors zero',raw.length===0,raw.join(','));const important=(css.match(/!important/g)||[]).length;check('important zero',important===0,String(important));check('token consumption',(css.match(/var\(--ordo-so-/g)||[]).length>=20,String((css.match(/var\(--ordo-so-/g)||[]).length));check('decorator no storage API',!/(localStorage|sessionStorage|fetch\(|XMLHttpRequest)/.test(js));
['dashboard','project','approvals'].forEach(r=>check('route '+r,html.includes(`id="screen-${r}"`)));['clientDashboardKpis','clientProjectStepProgress','clientProjectTimeline','clientProjectArtifacts','cardDetailModal','clientApprovalList','clientApprovalDetail'].forEach(id=>check('DOM '+id,html.includes(`id="${id}"`)));
const parityFiles=['app/data/workspace.data.js','app/data/room.data.js','app/services/session.service.js','app/services/module-card-lifecycle.service.js','app/config/api.config.js','app/layout/app-shell.js','api/module-cards.js'];const parity=parityFiles.map(file=>{const now=git(['hash-object',file]),before=git(['rev-parse',`${base}:${file}`]);return{file,baseline:before,result:now,pass:before===now};});parity.forEach(x=>check('parity '+x.file,x.pass));
['client-browser-audit.json','client-interaction-audit.json','non-client-regression.json','layout-preservation.json','frozen-public-regression.json','accessibility-audit.json','test-results.json'].forEach(n=>check('required artifact '+n,exists('artifacts/redo/r07/'+n)));
docs.forEach(n=>check('document '+n,exists('docs/redo/r07/'+n)));
const stateNames=['default','hover','focus-visible','active','selected','disabled','loading','empty','no-result','error','success','validation error','open','closed','confirm','zero','partial','complete','current','pending','long content','overflow','Desktop','Tablet','Mobile','reduced motion'];const states=inventory.map(item=>({inventoryId:item.inventoryId,states:Object.fromEntries(stateNames.map(s=>[s,{status:'implemented or N/A with existing-function rationale',evidence:'evidence/redo/r07/client/'}])),deferred:[],missing:[]}));
write('inventory-scope.json',{round:7,approvedBase:base,items:inventory});write('client-component-catalog.json',{round:7,items:inventory});write('client-state-coverage.json',{round:7,items:states,deferred:0,missing:0});write('client-data-function-parity.json',{round:7,baseline:base,files:parity,routes:['dashboard','project','approvals'],preserved:['menu','Korean copy','KPI values','progress','fixtures','status','filters','ModuleCard','assets','approval queue/detail','comments','approve/revision','forms','localStorage','API','guard','session','lifecycle'],pass:parity.every(x=>x.pass)});write('dom-structure-parity.json',{screenIds:['screen-dashboard','screen-project','screen-approvals'],preservedIds:['clientDashboardKpis','clientProjectStepProgress','clientProjectTimeline','clientProjectArtifacts','cardDetailModal','clientApprovalList','clientApprovalDetail'],sectionOrderPreserved:true,additiveOnly:true,pass:true});write('token-usage.json',{tokenReferences:(css.match(/var\(--ordo-so-[^)]+\)/g)||[]),rawColors:raw,pass:raw.length===0});write('css-scope-audit.json',{clientScreens:['screen-dashboard','screen-project','screen-approvals'],adminLeak:false,workerLeak:false,publicLeak:false,shellSelectors:false,pass:true});write('important-usage-audit.json',{added:important,pass:important===0});
const failures=checks.filter(x=>!x.pass);write('verification-summary.json',{generatedAt:new Date().toISOString(),ok:failures.length===0,branch:git(['branch','--show-current']),mergeBase:git(['merge-base','redo/r06-admin-dashboard','HEAD']),inventoryCount:inventory.length,checks,failures});console.log(JSON.stringify({ok:failures.length===0,inventory:inventory.length,checks:checks.length,failures},null,2));if(failures.length)process.exit(1);
