const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..','..','..'),art=path.join(root,'artifacts','redo','r09'),ev=path.join(root,'evidence','redo','r09');
const currentBase='http://127.0.0.1:4184/',baselineBase='http://127.0.0.1:4185/',round8Base='http://127.0.0.1:4186/';
const viewports={desktop1440:[1440,1000],desktop1280:[1280,900],tablet1024:[1024,1366],tablet768:[768,1024],mobile390:[390,844],mobile360:[360,800]},publicViewports={desktop:[1440,1000],tablet:[1024,1366],mobile:[390,844]};
const write=(name,value)=>{fs.mkdirSync(art,{recursive:true});fs.writeFileSync(path.join(art,name),JSON.stringify(value,null,2)+'\n');};
const rel=file=>path.relative(root,file).replaceAll('\\','/');
const shot=async(page,folder,name)=>{const file=path.join(ev,folder,name);fs.mkdirSync(path.dirname(file),{recursive:true});await page.screenshot({path:file,fullPage:true,animations:'disabled'});return rel(file);};
async function ready(page){await page.waitForFunction(()=>typeof window.navigate==='function'&&!!window.ORDO_SESSION_SERVICE);await page.evaluate(()=>document.fonts?.ready);await page.waitForTimeout(80);}
async function publicRoute(page,base,route){await page.goto(base+'#'+route);await ready(page);await page.locator('#screen-'+route).waitFor({state:'visible'});}
async function bootAt(page,base,role,route){await page.goto(base+'?r9='+Date.now()+'#select-workspace');await ready(page);await page.locator(`[data-ws-role="${role}"]`).click();await page.goto(base+'#'+route);await ready(page);}
async function boot(page,role,route){await bootAt(page,currentBase,role,route);}
async function publicSignature(page,route){
 return page.evaluate(({route})=>{const screen=document.getElementById('screen-'+route),round=n=>Number(n.toFixed(2)),box=n=>{const r=n.getBoundingClientRect();return[round(r.x),round(r.y),round(r.width),round(r.height)]},style=n=>{const s=getComputedStyle(n);return{display:s.display,color:s.color,background:s.backgroundColor,border:[s.borderTopWidth,s.borderTopStyle,s.borderTopColor],radius:s.borderRadius,fontFamily:s.fontFamily}},stable=value=>String(value||'').split(/\s+/).filter(x=>x&&!['active','hidden'].includes(x)).sort(),nodes=[screen,...screen.querySelectorAll('header,main,section,form,button,a,input,select,textarea')].slice(0,45),keys=[screen,...screen.children,...screen.querySelectorAll('header,main,form,h1,button')].slice(0,24);return{route,screenId:screen.id,dom:{elementCount:screen.querySelectorAll('*').length,idSequence:[...screen.querySelectorAll('[id]')].map(n=>n.id),tagSequence:[...screen.querySelectorAll('*')].map(n=>n.tagName),classSequence:[...screen.querySelectorAll('*')].map(n=>stable(n.className).join('.'))},text:screen.innerText.replace(/\s+/g,' ').trim(),contracts:{hrefs:[...screen.querySelectorAll('a')].map(n=>n.getAttribute('href')||''),forms:[...screen.querySelectorAll('form')].map(n=>({id:n.id,name:n.getAttribute('name')||'',controls:[...n.elements].map(e=>({id:e.id,name:e.name,type:e.type}))})),buttons:[...screen.querySelectorAll('button')].map(n=>({id:n.id,type:n.type,name:n.innerText.trim()||n.getAttribute('aria-label')||''}))},styles:nodes.map(n=>({tag:n.tagName,id:n.id,classes:stable(n.className),style:style(n)})),boxes:keys.map(n=>({tag:n.tagName,id:n.id,box:box(n)})),page:{scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight,clientWidth:document.documentElement.clientWidth,clientHeight:document.documentElement.clientHeight,overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth}};},{route});
}
const compare=(baseline,current)=>{const differences=[];for(const key of ['screenId','dom','text','contracts','styles','boxes'])if(JSON.stringify(baseline[key])!==JSON.stringify(current[key]))differences.push(key);return{domSame:JSON.stringify(baseline.dom)===JSON.stringify(current.dom),textSame:baseline.text===current.text,styleSame:JSON.stringify(baseline.styles)===JSON.stringify(current.styles),boxSame:JSON.stringify(baseline.boxes)===JSON.stringify(current.boxes),formContractSame:JSON.stringify(baseline.contracts)===JSON.stringify(current.contracts),differences};};
module.exports={root,art,ev,currentBase,baselineBase,round8Base,viewports,publicViewports,write,shot,ready,publicRoute,bootAt,boot,publicSignature,compare};
