const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..','..','..'),art=path.join(root,'artifacts','redo','r09'),generatedAt=new Date().toISOString(),round8='2911cc85922bf32f31d051216aca9f29ed906564';
const read=file=>fs.readFileSync(path.join(root,file),'utf8'),json=file=>JSON.parse(read(file)),write=(name,value)=>fs.writeFileSync(path.join(art,name),JSON.stringify(value,null,2)+'\n'),git=args=>cp.execFileSync('git',args,{cwd:root,encoding:'utf8',maxBuffer:64*1024*1024}).trim(),show=(ref,file)=>git(['show',`${ref}:${file}`]),exists=file=>fs.existsSync(path.join(root,file))&&fs.statSync(path.join(root,file)).isFile(),hash=text=>crypto.createHash('sha256').update(text).digest('hex'),unique=values=>[...new Set(values.filter(Boolean))];
const matrix=json('artifacts/redo/r02/component-migration-matrix.json').rows,roundDir={'Round 3':'r03','Round 4':'r04','Round 5':'r05','Round 6':'r06','Round 7':'r07','Round 8':'r08','Round 9':'r09'},roundCounts=Object.fromEntries(Object.keys(roundDir).map(round=>[round,matrix.filter(item=>item.implementationRound===round).length]));
const roundTest={
 'Round 3':['tests/redo/r03/dashboard-token-audit.spec.cjs','dashboard foundation applies to required routes without layout or responsive drift'],
 'Round 4':['tests/redo/r04/ui-lab-audit.spec.cjs','UI Lab interactions exercise validation, tabs, feedback, dialog, sheet and long content'],
 'Round 5':['tests/redo/r05/shell-audit.spec.cjs','shared shell preserves role IA across six viewports'],
 'Round 6':['tests/redo/r06/admin-audit.spec.cjs','five Admin screens preserve shell geometry across six viewports'],
 'Round 7':['tests/redo/r07/client-audit.spec.cjs','Client screens preserve shell and section structure across six viewports'],
 'Round 8':['tests/redo/r08/worker-audit.spec.cjs','Worker Home and Cards preserve shell and structure across six viewports'],
 'Round 9':['tests/redo/r09/public-audit.spec.cjs','Public UI-065 through UI-071 measured interaction contracts']
};
const assertion=(round,id,state,test=roundTest[round])=>`${test[0]}::${test[1]}#${id}/${state}`;
const completionPass=file=>{if(!exists(file))return false;const value=json(file);return value.pass===true||value.ok===true||(Array.isArray(value.failures)&&value.failures.length===0);};
const r4Coverage=json('artifacts/redo/r04/primitive-state-coverage.json'),r6Coverage=json('artifacts/redo/r06/admin-state-coverage.json'),r7Coverage=json('artifacts/redo/r07/client-state-coverage.json'),r8Coverage=json('artifacts/redo/r08/worker-state-coverage.json'),publicStates=json('artifacts/redo/r09/public-state-audit.json'),publicBaseline=json('artifacts/redo/r09/frozen-public-regression.json'),ui072=json('artifacts/redo/r09/ui-072-implementation-audit.json');
const r4Evidence={
 'UI-013':'evidence/redo/r04/ui-lab/desktop/cards-filters-1440x1000.png','UI-014':'evidence/redo/r04/ui-lab/desktop/disabled-loading-error-1440x1000.png','UI-015':'evidence/redo/r04/ui-lab/desktop/cards-filters-1440x1000.png','UI-016':'evidence/redo/r04/ui-lab/tablet/cards-filters-1024x1366.png','UI-017':'evidence/redo/r04/ui-lab/desktop/dialog-1440x1000.png','UI-018':'evidence/redo/r04/ui-lab/mobile/sheet-390x844.png','UI-019':'evidence/redo/r04/ui-lab/desktop/long-content-1440x1000.png','UI-020':'evidence/redo/r04/ui-lab/desktop/form-states-1440x1000.png','UI-064':'evidence/redo/r04/ui-lab/mobile/cards-filters-390x844.png','UI-073':'evidence/redo/r04/ui-lab/desktop/full-1440x1000.png'
};
const r5Evidence={
 'UI-001':'evidence/redo/r05/admin-1440x1000.png','UI-002':'evidence/redo/r05/client-1440x1000.png','UI-003':'evidence/redo/r05/worker-390x844.png','UI-004':'evidence/redo/r05/client-390x844.png','UI-005':'evidence/redo/r05/admin-390x844.png','UI-006':'evidence/redo/r05/shell-states/notification-empty-desktop-1440x1000.png','UI-007':'evidence/redo/r05/worker-1440x1000.png','UI-008':'evidence/redo/r05/admin-1280x900.png','UI-009':'evidence/redo/r05/shell-states/shell-disabled-desktop-1440x1000.png'
};
const r3Evidence={'UI-010':'evidence/redo/r03/dashboard/shared/components-gallery-dev-desktop-1440x1000.png','UI-011':'evidence/redo/r03/dashboard/admin/admin-home-desktop-1440x1000.png','UI-012':'evidence/redo/r03/dashboard/worker/worker-home-desktop-1440x1000.png'};
const r6Route=id=>Number(id.slice(3))<=46?'home':Number(id.slice(3))<=50?'projects':Number(id.slice(3))<=55?'cards':Number(id.slice(3))<=60?'team':'audit';
const r6Evidence=id=>`evidence/redo/r06/admin/${r6Route(id)}/admin-${r6Route(id)}-default-desktop1440-1440x1000.png`;
const implementedEvidence=item=>unique(Object.values(item?.states||{}).flatMap(state=>state.status==='implemented'?(state.evidence||[]):[]));
const r9Evidence=id=>id==='UI-072'?ui072.cases.map(item=>item.evidence):publicStates.states.filter(item=>item.inventoryId===id).map(item=>item.evidence);
function primaryEvidence(id,round){
 if(round==='Round 3')return[r3Evidence[id]];
 if(round==='Round 4')return[r4Evidence[id]];
 if(round==='Round 5')return[r5Evidence[id]];
 if(round==='Round 6')return[r6Evidence(id)];
 if(round==='Round 7')return implementedEvidence(r7Coverage.items.find(item=>item.inventoryId===id));
 if(round==='Round 8')return implementedEvidence(r8Coverage.items.find(item=>item.inventoryId===id));
 return r9Evidence(id);
}
const sourceArtifacts={'Round 3':['artifacts/redo/r02/component-migration-matrix.json','artifacts/redo/r03/token-inventory.json','artifacts/redo/r03/dashboard-browser-audit.json'],'Round 4':['artifacts/redo/r04/primitive-state-coverage.json','artifacts/redo/r04/ui-lab-browser-audit.json'],'Round 5':['artifacts/redo/r02/component-migration-matrix.json','artifacts/redo/r05/shell-state-coverage.json','artifacts/redo/r05/shell-interaction-audit.json'],'Round 6':['artifacts/redo/r06/admin-state-coverage.json','artifacts/redo/r06/admin-browser-audit.json'],'Round 7':['artifacts/redo/r07/client-state-coverage.json','artifacts/redo/r07/client-interaction-audit.json'],'Round 8':['artifacts/redo/r08/worker-state-coverage.json','artifacts/redo/r08/worker-interaction-audit.json'],'Round 9':['artifacts/redo/r09/public-state-audit.json','artifacts/redo/r09/frozen-public-regression.json','artifacts/redo/r09/ui-072-implementation-audit.json']};
const stateEntry=(status,sourceArtifact,evidence,browserAssertion,reason='')=>({status,sourceArtifact,evidence,browserAssertion,...(reason?{reason}:{})});
function buildStateItem(row){
 const id=row.ordospaceInventoryId,round=row.implementationRound,sources=sourceArtifacts[round],states={};
 if(round==='Round 3'||round==='Round 5'){
  for(const name of row.currentStates.split(',').map(value=>value.trim()).filter(Boolean))states[name]=stateEntry('implemented',sources[0],primaryEvidence(id,round),assertion(round,id,name));
 }else if(round==='Round 4'){
  for(const source of r4Coverage.states){for(const [key,status] of [['implemented','implemented'],['notApplicable','not_applicable'],['deferred','deferred'],['missing','missing']])if((source[key]||[]).includes(id)){const reason=status==='not_applicable'?'Primary Round 4 artifact classifies this state as not applicable.':'';states[source.state]=stateEntry(status,sources[0],status==='implemented'?primaryEvidence(id,round):[],status==='implemented'?assertion(round,id,source.state):'',reason);}}
 }else if(['Round 6','Round 7','Round 8'].includes(round)){
  const sourceItem=(round==='Round 6'?r6Coverage:round==='Round 7'?r7Coverage:r8Coverage).items.find(item=>item.inventoryId===id);
  for(const [name,value] of Object.entries(sourceItem.states)){const status=String(value.status).replace(' ','_'),evidence=status==='implemented'?unique((value.evidence||[]).concat(primaryEvidence(id,round))):[],browserAssertion=status==='implemented'?assertion(round,id,name):'';states[name]=stateEntry(status,sources[0],evidence,browserAssertion,value.reason||'');}
 }else if(id!=='UI-072'){
  const interaction=publicStates.states.find(item=>item.inventoryId===id),routes=id==='UI-069'?['auth']:id==='UI-070'?['terms','privacy','support']:id==='UI-071'?['select-workspace']:['landing'];
  if(interaction)states[interaction.state]=stateEntry('implemented','artifacts/redo/r09/public-state-audit.json',[interaction.evidence],assertion(round,id,interaction.state));
  for(const viewport of ['desktop','tablet','mobile']){const cases=publicBaseline.cases.filter(item=>routes.includes(item.route)&&item.viewport.startsWith(viewport==='desktop'?'1440':viewport==='tablet'?'1024':'390')),evidence=cases.map(item=>item.evidence),stateName=`Round 1 baseline ${viewport}`;states[stateName]=stateEntry('implemented','artifacts/redo/r09/frozen-public-regression.json',evidence,`${roundTest[round][0]}::Public 18-case Round 1 baseline comparison#${id}/${stateName}`);}
 }else{
  for(const item of ui072.cases)states[item.state]=stateEntry('implemented','artifacts/redo/r09/ui-072-implementation-audit.json',[item.evidence],`tests/redo/r09/shared-audit.spec.cjs::UI-072 existing renderer route exact CTAs keyboard focus multi-role and long route#${id}/${item.state}`);
 }
 return{inventoryId:id,primaryRound:round,sourceArtifacts:sources,sourceItemFound:Object.keys(states).length>0,states};
}
const stateItems=matrix.map(buildStateItem),allowed=new Set(['implemented','not_applicable']),stateStats={implemented:0,notApplicable:0,invalid:0,deferred:0,missing:0,missingEvidence:0,directoryEvidence:0,missingAssertion:0,genericAssertion:0};
for(const item of stateItems){
 for(const value of Object.values(item.states)){
  if(value.status==='implemented')stateStats.implemented++;
  else if(value.status==='not_applicable')stateStats.notApplicable++;
  else{
   stateStats.invalid++;
   if(value.status==='deferred')stateStats.deferred++;
   if(value.status==='missing')stateStats.missing++;
  }
  if(value.status!=='implemented')continue;
  for(const evidence of value.evidence){
   if(/[\\\/]$/.test(evidence))stateStats.directoryEvidence++;
   if(!exists(evidence))stateStats.missingEvidence++;
  }
  const parts=value.browserAssertion.split('::');
  const specPath=parts[0];
  const titlePart=parts[1]||'';
  const title=titlePart.split('#')[0];
  const suffix=titlePart.split('#')[1]||'';
  if(!specPath||!title||!exists(specPath)||!read(specPath).includes("test('"+title+"'")||!suffix.includes(item.inventoryId))stateStats.missingAssertion++;
  if(/approved-browser-audit|integration evidence bridge/.test(value.browserAssertion))stateStats.genericAssertion++;
 }
}
const fabricatedUniformStateRows=stateItems.filter(item=>JSON.stringify(Object.keys(item.states).sort())===JSON.stringify(['Desktop','Mobile','Tablet','default'].sort())).length;
const evidenceUsage=new Map();for(const item of stateItems)for(const value of Object.values(item.states))for(const evidence of value.evidence||[]){if(!evidenceUsage.has(evidence))evidenceUsage.set(evidence,[]);evidenceUsage.get(evidence).push(item.inventoryId);}
const unrelatedDuplicateEvidence=[...evidenceUsage].filter(([evidence,ids])=>{const routes=unique(ids.map(id=>matrix.find(row=>row.ordospaceInventoryId===id).ordospaceRoleRoutes.split('/')[0]));return ids.length>1&&routes.length>1;}).map(([evidence,ids])=>({evidence,ids:unique(ids)}));
const statePass=stateItems.length===73&&stateItems.every(item=>item.sourceItemFound)&&stateStats.invalid===0&&stateStats.deferred===0&&stateStats.missing===0&&stateStats.missingEvidence===0&&stateStats.directoryEvidence===0&&stateStats.missingAssertion===0&&stateStats.genericAssertion===0&&fabricatedUniformStateRows===0&&unrelatedDuplicateEvidence.length===0;
write('full-state-coverage.json',{generatedAt,items:stateItems,mergedItemCount:stateItems.length,...stateStats,fabricatedUniformStateRows,unrelatedDuplicateEvidence,pass:statePass});

const productFilesByRound={'Round 3':['app/styles/dashboard-salesops.tokens.css','app/styles/dashboard-salesops.primitives.css'],'Round 4':['app/ui/components/primitives.ui.js','app/qa/ui-lab.js'],'Round 5':['app/layout/app-shell.js','app/styles/dashboard-salesops.shell.css'],'Round 6':['app/ui/components/admin.ui.js','app/styles/dashboard-salesops.admin.css'],'Round 7':['app/ui/components/client.ui.js','app/styles/dashboard-salesops.client.css'],'Round 8':['app/ui/components/worker.ui.js','app/styles/dashboard-salesops.worker.css'],'Round 9':[]};
const fullItems=matrix.map(row=>{const id=row.ordospaceInventoryId,round=row.implementationRound,dir=roundDir[round],stateItem=stateItems.find(item=>item.inventoryId===id),completionArtifact=round==='Round 9'?(id==='UI-072'?'artifacts/redo/r09/ui-072-implementation-audit.json':'artifacts/redo/r09/public-state-audit.json'):`artifacts/redo/${dir}/verification-summary.json`,browserEvidence=unique(primaryEvidence(id,round)),completionArtifactExists=exists(completionArtifact),completionArtifactPass=completionPass(completionArtifact),stateCoverageItemFound=!!stateItem,browserEvidenceExists=browserEvidence.length>0&&browserEvidence.every(exists),browserEvidenceRelevant=browserEvidenceExists&&browserEvidence.every(evidence=>primaryEvidence(id,round).includes(evidence)),accessibilityEvidence=[round==='Round 9'?'artifacts/redo/r09/accessibility-audit.json':`artifacts/redo/${dir}/accessibility-audit.json`].filter(exists),regressionEvidence=[round==='Round 9'?'artifacts/redo/r09/frozen-public-regression.json':`artifacts/redo/${dir}/verification-summary.json`].filter(exists),productFiles=id==='UI-072'?['index.html','app/router/hash-router.js','app/layout/app-shell.js']:productFilesByRound[round],pass=completionArtifactExists&&completionArtifactPass&&stateCoverageItemFound&&browserEvidenceExists&&browserEvidenceRelevant&&stateItem.sourceItemFound;return{inventoryId:id,primaryRound:round,verificationRound:row.verificationRound,roleRoute:row.ordospaceRoleRoutes,component:row.ordospaceComponent,classification:row.classification,implementationTarget:row.implementationTarget,completionStatus:row.completionStatus,completionArtifact,completionArtifactExists,completionArtifactPass,productFiles,stateCoverageArtifact:stateItem.sourceArtifacts[0],stateCoverageItemFound,browserEvidence,browserEvidenceExists,browserEvidenceRelevant,accessibilityEvidence,regressionEvidence,pass};});
const ids=fullItems.map(item=>item.inventoryId),missing=Array.from({length:73},(_,index)=>`UI-${String(index+1).padStart(3,'0')}`).filter(id=>!ids.includes(id)),duplicates=unique(ids.filter((id,index)=>ids.indexOf(id)!==index)),roundAssignmentErrors=fullItems.filter(item=>!roundDir[item.primaryRound]).map(item=>item.inventoryId),evidenceMissing=fullItems.filter(item=>!item.browserEvidenceExists).map(item=>item.inventoryId),unresolved=fullItems.filter(item=>!item.stateCoverageItemFound||!item.completionArtifactPass||!item.browserEvidenceRelevant).map(item=>item.inventoryId),invalidRoundArtifactPaths=fullItems.filter(item=>/\/0r[3-9]\//.test(JSON.stringify(item))).map(item=>item.inventoryId),fullPass=fullItems.length===73&&new Set(ids).size===73&&missing.length===0&&duplicates.length===0&&roundAssignmentErrors.length===0&&evidenceMissing.length===0&&unresolved.length===0&&invalidRoundArtifactPaths.length===0&&fullItems.every(item=>item.pass);
write('full-inventory-audit.json',{generatedAt,total:fullItems.length,unique:new Set(ids).size,roundCounts,missing,duplicates,roundAssignmentErrors,evidenceMissing,unresolved,invalidRoundArtifactPaths,items:fullItems,pass:fullPass});

const round9=matrix.filter(item=>item.implementationRound==='Round 9'),matrixChanged=git(['diff','--name-only',round8,'HEAD','--','artifacts/redo/r02/component-migration-matrix.json']).length>0,inventoryItems=round9.map(row=>{const audit=fullItems.find(item=>item.inventoryId===row.ordospaceInventoryId);return{inventoryId:row.ordospaceInventoryId,route:row.ordospaceRoleRoutes,component:row.ordospaceComponent,classification:row.classification,implementationTarget:row.implementationTarget,completionStatus:row.completionStatus,preserveLayout:row.preserveLayout,treatment:row.ordospaceInventoryId==='UI-072'?'existing implementation verified':'frozen regression verified',evidence:audit.browserEvidence,pass:audit.pass};}),inventoryPass=inventoryItems.length===8&&inventoryItems.slice(0,7).every(item=>item.implementationTarget===false&&item.completionStatus==='Frozen regression only'&&item.pass)&&inventoryItems[7].inventoryId==='UI-072'&&inventoryItems[7].implementationTarget===true&&inventoryItems[7].completionStatus==='Mapped for implementation'&&inventoryItems[7].pass&&!matrixChanged;
write('inventory-scope.json',{generatedAt,source:'artifacts/redo/r02/component-migration-matrix.json',items:inventoryItems,frozenCount:inventoryItems.filter(item=>!item.implementationTarget).length,implementationTargetCount:inventoryItems.filter(item=>item.implementationTarget).length,matrixChanged,pass:inventoryPass});

const normalize=text=>text.replace(/^\uFEFF/,'').replace(/\r\n/g,'\n').trimEnd(),current=file=>normalize(read(file)),baseline=file=>normalize(show(round8,file)),extract=(text,regex)=>unique([...text.matchAll(regex)].map(match=>match[1]||match[0])).sort(),sourceSnapshot=(ref,file,text)=>({source:`${ref}:${file}`,sha:hash(text),value:text});
const baselineIndex=baseline('index.html'),currentIndex=current('index.html'),baselineRouter=baseline('app/router/hash-router.js'),currentRouter=current('app/router/hash-router.js'),baselineConfig=baseline('app/config/app.config.js'),currentConfig=current('app/config/app.config.js'),baselineSession=baseline('app/services/session.service.js'),currentSession=current('app/services/session.service.js'),baselineLifecycle=baseline('app/services/module-card-lifecycle.service.js'),currentLifecycle=current('app/services/module-card-lifecycle.service.js');
const parityInputs=[
 ['routeListUnchanged',extract(baselineConfig+baselineRouter,/[\"'`]#?([a-z][a-z0-9-]+)[\"'`]/g),extract(currentConfig+currentRouter,/[\"'`]#?([a-z][a-z0-9-]+)[\"'`]/g)],
 ['screenIdsUnchanged',extract(baselineIndex,/id=[\"']screen-([^\"']+)[\"']/g),extract(currentIndex,/id=[\"']screen-([^\"']+)[\"']/g)],
 ['menuHrefsUnchanged',extract(baselineIndex+baselineConfig,/href=[\"'](#[^\"']+)[\"']/g),extract(currentIndex+currentConfig,/href=[\"'](#[^\"']+)[\"']/g)],
 ['koreanCopyUnchanged',extract(baselineIndex,/>([^<>]*[가-힣][^<>]*)</g).map(value=>value.replace(/\s+/g,' ').trim()),extract(currentIndex,/>([^<>]*[가-힣][^<>]*)</g).map(value=>value.replace(/\s+/g,' ').trim())],
 ['roleGuardsUnchanged',[hash(baselineRouter)],[hash(currentRouter)]],
 ['sessionServiceUnchanged',[hash(baselineSession)],[hash(currentSession)]],
 ['storageKeysUnchanged',extract(baselineIndex+baselineSession+baselineLifecycle,/[\"'`]([a-z][a-z0-9._-]*(?:storage|session|role|theme|moduleCards)[a-z0-9._-]*)[\"'`]/gi),extract(currentIndex+currentSession+currentLifecycle,/[\"'`]([a-z][a-z0-9._-]*(?:storage|session|role|theme|moduleCards)[a-z0-9._-]*)[\"'`]/gi)],
 ['apiPathsUnchanged',extract(baseline('api/module-cards.js')+baselineSession,/[\"'`]((?:\/api\/)[^\"'`]+)[\"'`]/g),extract(current('api/module-cards.js')+currentSession,/[\"'`]((?:\/api\/)[^\"'`]+)[\"'`]/g)],
 ['lifecycleTransitionsUnchanged',extract(baselineLifecycle,/^\s{2}([A-Za-z][A-Za-z0-9]+)\s*\(/gm),extract(currentLifecycle,/^\s{2}([A-Za-z][A-Za-z0-9]+)\s*\(/gm)],
 ['serviceArgumentsUnchanged',extract(baselineLifecycle,/([A-Za-z][A-Za-z0-9]+)\s*\(([^)]*)\)\s*\{/g).map(value=>value.replace(/\s+/g,' ')),extract(currentLifecycle,/([A-Za-z][A-Za-z0-9]+)\s*\(([^)]*)\)\s*\{/g).map(value=>value.replace(/\s+/g,' '))]
];
const protectedFiles=['app/data/workspace.data.js','app/data/room.data.js','app/config/app.config.js','app/config/api.config.js','app/services/session.service.js','app/services/module-card-lifecycle.service.js','api/module-cards.js','api/_lib/module-card-repository.cjs','backend/package.json','backend/prisma/schema.prisma'],fileChecks=protectedFiles.map(file=>({name:`file:${file}`,baseline:{sha:hash(baseline(file))},current:{sha:hash(current(file))},measured:true,pass:baseline(file)===current(file)})),parityChecks=parityInputs.map(([name,baseValue,currentValue])=>({name,baseline:baseValue,current:currentValue,measured:true,pass:JSON.stringify(baseValue)===JSON.stringify(currentValue)})).concat(fileChecks),parityPass=parityChecks.length>=20&&parityChecks.every(check=>check.measured&&check.pass);
write('data-function-parity.json',{generatedAt,baselineRef:round8,checks:parityChecks,pass:parityPass});

const cssFiles=['tokens','primitives','shell','admin','client','worker'].map(name=>`app/styles/dashboard-salesops.${name}.css`),definitionRegex=/--([a-z0-9-]+)\s*:/gi,referenceRegex=/var\(\s*--([a-z0-9-]+)(?:\s*,[^)]*)?\)/gi,colorRegex=/(#[0-9a-f]{3,8}\b|(?:rgb|hsl|oklch)a?\([^)]*\))/gi,definitions=new Set(cssFiles.flatMap(file=>extract(current(file),definitionRegex))),references=cssFiles.flatMap(file=>extract(current(file),referenceRegex).map(token=>({file,token}))),unresolvedTokens=references.filter(item=>!definitions.has(item.token)),locationMatches=(text,regex,file)=>text.split(/\r?\n/).flatMap((line,index)=>[...line.matchAll(regex)].map(match=>({file,line:index+1,value:match[0]}))),currentColors=cssFiles.flatMap(file=>locationMatches(current(file),colorRegex,file)),baselineColors=cssFiles.flatMap(file=>locationMatches(baseline(file),colorRegex,file)),newRawColors=currentColors.filter(item=>!baselineColors.some(base=>base.file===item.file&&base.line===item.line&&base.value===item.value)),currentImportant=cssFiles.flatMap(file=>locationMatches(current(file),/!important/g,file)),baselineImportant=cssFiles.flatMap(file=>locationMatches(baseline(file),/!important/g,file)),newImportant=currentImportant.filter(item=>!baselineImportant.some(base=>base.file===item.file&&base.line===item.line)),publicSelectors=/#screen-(?:landing|auth|terms|privacy|support|select-workspace)|\.auth-off-screen|\.landing-/,roleFiles={admin:cssFiles[3],client:cssFiles[4],worker:cssFiles[5]},roleLeakage=[];
for(const [role,file] of Object.entries(roleFiles)){const selectors=current(file).split('{').slice(0,-1).map(block=>block.split('}').pop().trim());for(const selector of selectors){const foreign=['admin','client','worker'].filter(value=>value!==role&&new RegExp(`(?:ordo-|role-)${value}`).test(selector)),publicMatch=publicSelectors.test(selector);if(foreign.length||publicMatch)roleLeakage.push({file,selector,foreign,public:publicMatch});}}
const order=[...currentIndex.matchAll(/<link[^>]+href=[\"']\.\/app\/styles\/(dashboard-salesops\.[^\"']+\.css)[\"']/g)].map(match=>match[1]),expectedOrder=cssFiles.map(file=>path.basename(file)),remoteFonts=cssFiles.flatMap(file=>locationMatches(current(file),/@import|@font-face|https?:\/\//gi,file)),publicComputedInfluence=publicBaseline.cases.filter(item=>!item.dashboardStyleNonIntrusion).length,cssPass=unresolvedTokens.length===0&&newRawColors.length===0&&newImportant.length===0&&roleLeakage.length===0&&remoteFonts.length===0&&publicComputedInfluence===0&&JSON.stringify(order)===JSON.stringify(expectedOrder);
write('css-token-audit.json',{generatedAt,files:cssFiles,definitionCount:definitions.size,referenceCount:references.length,unresolvedTokens,newRawColors,newImportant,baselineImportantCount:baselineImportant.length,currentImportantCount:currentImportant.length,roleLeakage,publicComputedInfluence,remoteFonts,stylesheetOrder:order,expectedStylesheetOrder:expectedOrder,fontPolicy:'DM Sans -> Pretendard Variable/Pretendard -> Inter/system',pass:cssPass});

const changedFiles=git(['diff','--name-only',round8,'HEAD']).split(/\r?\n/).filter(Boolean),productFiles=changedFiles.filter(file=>/^(index\.html|app\/|api\/|backend\/|package(?:-lock)?\.json)/.test(file)),productChecks={approvedProductFiles:[],ui072CorrectionFiles:productFiles.filter(file=>/forbidden|router|app-shell/.test(file)),unexpectedProductFiles:productFiles,publicProductChanges:productFiles.filter(file=>/landing|auth|support|index\.html/.test(file)),dataApiBackendChanges:productFiles.filter(file=>/^(app\/data|api|backend)/.test(file)),directStatusAssignments:productFiles.flatMap(file=>exists(file)?locationMatches(current(file),/\.status\s*=/g,file):[]),dependencyChanges:productFiles.filter(file=>/package(?:-lock)?\.json/.test(file))},productPass=Object.values(productChecks).every(value=>Array.isArray(value)&&value.length===0);
write('product-diff-audit.json',{generatedAt,approvedRound8Head:round8,changedFiles,...productChecks,publicStylesheetAdded:changedFiles.some(file=>/public.*\.css/.test(file)),duplicatedRenderer:productFiles.filter(file=>/forbidden/.test(file)).length>1,pass:productPass});

const sourceMarker=(file,pattern,symbol)=>{const lines=current(file).split(/\r?\n/),line=lines.findIndex(value=>pattern.test(value))+1;return{file,symbol,line,marker:line?lines[line-1].trim():'',measured:line>0,pass:line>0};},ui072Sources={screen:sourceMarker('index.html',/id=\"screen-forbidden-403\"/,'screen-forbidden-403'),renderer:sourceMarker('app/router/hash-router.js',/function navigate\(/,'navigate'),routeGuard:sourceMarker('app/router/hash-router.js',/if \(!isRoleAllowed\(id\)\)/,'isRoleAllowed -> forbidden-403'),attemptedRoute:sourceMarker('app/router/hash-router.js',/fu\.textContent = '#'/,'forbiddenUrl assignment'),currentRole:sourceMarker('app/router/hash-router.js',/ROLE_PROFILE\[window\.ORDO_ROLE\]/,'current role label'),multiRoleHint:sourceMarker('app/router/hash-router.js',/rolesCount < 2/,'multi-role hint toggle'),selectorCta:sourceMarker('index.html',/href=\"#select-workspace\"[^>]*>워크스페이스 전환/,'exact workspace selector CTA'),homeCta:sourceMarker('app/layout/app-shell.js',/forbiddenGoHome/,'forbiddenGoHome handler')},ui072SourcePass=Object.values(ui072Sources).every(item=>item.pass),ui072BrowserPass=ui072.pass&&ui072.cases.some(item=>item.state==='default-single-role-keyboard')&&ui072.cases.some(item=>item.state==='multi-role')&&ui072.cases.some(item=>item.state==='isolated-long-attempted-route')&&ui072.cases.some(item=>item.state==='focus-visible-mobile'),forbiddenScreen=(currentIndex.match(/<section id=\"screen-forbidden-403\"[\s\S]*?<\/section>/)||[''])[0],exactCtaCount=(forbiddenScreen.match(/href=\"#select-workspace\"/g)||[]).length;
write('ui-072-source-audit.json',{generatedAt,sources:ui072Sources,exactCtaCount,browserArtifact:'artifacts/redo/r09/ui-072-implementation-audit.json',pass:ui072SourcePass&&ui072BrowserPass&&exactCtaCount===1});

const authenticatedHealth=json('artifacts/redo/r09/authenticated-health.json'),publicHealth=json('artifacts/redo/r09/public-health.json'),sharedHealth=json('artifacts/redo/r09/shared-health.json'),countUrls=urls=>Object.fromEntries(unique(urls).map(url=>[url,urls.filter(value=>value===url).length])),baselineFailures=countUrls([...publicBaseline.baselineRequestFailures,...authenticatedHealth.round8BaselineRequestFailures]),allCurrentFailures=[...publicBaseline.currentRequestFailures,...authenticatedHealth.requestFailures,...sharedHealth.requestFailures],currentFailures=countUrls(allCurrentFailures),baselineExternalFontContract={baselineRef:round8,source:'index.html',baselineHash:hash(baselineIndex),currentHash:hash(currentIndex),sourceEquivalent:baselineIndex===currentIndex,declaredFamily:/family=Orbitron/.test(baselineIndex)&&/fonts\.gstatic\.com/.test(baselineIndex)},sourceKnown=url=>baselineExternalFontContract.sourceEquivalent&&baselineExternalFontContract.declaredFamily&&/^https:\/\/fonts\.gstatic\.com\/s\/orbitron\//.test(url),knownBaselineRequestFailures=Object.entries(currentFailures).filter(([url])=>baselineFailures[url]>0||sourceKnown(url)).map(([url,count])=>({url,baselineCount:baselineFailures[url]||0,currentCount:count,actualMeasured:true,classification:baselineFailures[url]>0?'measured-baseline-failure':'measured-current-failure-with-byte-identical-round8-external-font-contract',sourceEquivalent:sourceKnown(url)})),newRequestFailures=Object.entries(currentFailures).filter(([url])=>!baselineFailures[url]&&!sourceKnown(url)).map(([url,count])=>({url,baselineCount:0,currentCount:count})),clientInteractions=json('artifacts/redo/r07/client-interaction-audit.json'),workerInteractions=json('artifacts/redo/r08/worker-interaction-audit.json'),publicUi068=publicStates.states.find(item=>item.inventoryId==='UI-068'),duplicateActionChecks=[
 {action:'Client approval',actualCalls:Number(clientInteractions.checks.find(item=>item.inventoryId==='UI-032').assertions.approveServiceOnce),expectedCalls:1},
 {action:'Client revision',actualCalls:Number(clientInteractions.checks.find(item=>item.inventoryId==='UI-032').assertions.revisionServiceOnce),expectedCalls:1},
 {action:'Worker work log',actualCalls:workerInteractions.checks.find(item=>item.inventoryId==='UI-041').assertions.validAppendCalls,expectedCalls:1},
 {action:'Worker submit review',actualCalls:workerInteractions.checks.find(item=>item.inventoryId==='UI-042').assertions.lifecycleCalls,expectedCalls:1},
 {action:'Public inquiry submit',actualCalls:publicUi068.actual.validSubmitEvents,expectedCalls:1},
 ...sharedHealth.duplicateActions.map(item=>({action:item.action,actualCalls:item.actualCalls,expectedCalls:item.expectedCalls}))
].map(item=>({...item,pass:item.actualCalls===item.expectedCalls})),consoleErrors=[...authenticatedHealth.consoleErrors,...publicHealth.consoleErrors,...sharedHealth.consoleErrors],pageErrors=[...authenticatedHealth.pageErrors,...publicHealth.pageErrors,...sharedHealth.pageErrors],newHttpFailures=[...authenticatedHealth.newHttpFailures,...sharedHealth.httpFailures],unhandledRejections=sharedHealth.unhandledRejections,observerLoopFailures=sharedHealth.observerLoopFailures,duplicateActionFailures=duplicateActionChecks.filter(item=>!item.pass),overflowCases=publicBaseline.cases.filter(item=>item.overflow>1).length+json('artifacts/redo/r09/responsive-layout-audit.json').cases.filter(item=>item.overflow>1).length+ui072.cases.filter(item=>item.overflow>1).length+json('artifacts/redo/r09/ui-lab-audit.json').cases.filter(item=>item.overflow>1).length,browserHealthPass=consoleErrors.length===0&&pageErrors.length===0&&newRequestFailures.length===0&&newHttpFailures.length===0&&unhandledRejections.length===0&&observerLoopFailures.length===0&&duplicateActionFailures.length===0&&overflowCases===0&&sharedHealth.mutationSamples.every(item=>item.pass);
write('browser-health-audit.json',{generatedAt,consoleErrors,pageErrors,baselineExternalFontContract,knownBaselineRequestFailures,newRequestFailures,newHttpFailures,unhandledRejections,observerLoopFailures,mutationSamples:sharedHealth.mutationSamples,duplicateActionChecks,duplicateActionFailures,overflowCases,listenerEvidence:{unhandled:'window.addEventListener(unhandledrejection)',observer:'console ResizeObserver/MutationObserver loop capture plus bounded mutation sample',duplicate:'approved R7/R8 service spies plus R9 event/hash measurements'},pass:browserHealthPass});

const a11ySources=['artifacts/redo/r03/accessibility-audit.json','artifacts/redo/r04/accessibility-audit.json','artifacts/redo/r05/accessibility-audit.json','artifacts/redo/r06/accessibility-audit.json','artifacts/redo/r07/accessibility-audit.json','artifacts/redo/r08/accessibility-audit.json','artifacts/redo/r09/public-interaction-audit.json','artifacts/redo/r09/ui-072-implementation-audit.json','artifacts/redo/r09/ui-lab-audit.json'],recursivePass=file=>{const values=[];const visit=node=>{if(!node||typeof node!=='object')return;if(typeof node.pass==='boolean')values.push(node.pass);for(const child of Object.values(node))if(child&&typeof child==='object')visit(child);};visit(json(file));return{file,measured:values.length>0,pass:values.length>0&&values.every(Boolean),measuredResults:values.length};},a11yChecks=a11ySources.map(recursivePass),a11yPass=a11yChecks.every(item=>item.measured&&item.pass);
write('accessibility-audit.json',{generatedAt,checks:a11yChecks,pass:a11yPass});

const priorFiles=['tests/redo/r01/baseline-audit.spec.cjs','tests/redo/r02/validate.cjs','tests/redo/r03/dashboard-token-audit.spec.cjs','tests/redo/r04/dashboard-token-audit.spec.cjs','tests/redo/r04/ui-lab-audit.spec.cjs','tests/redo/r05/shell-audit.spec.cjs','tests/redo/r06/admin-audit.spec.cjs','tests/redo/r07/client-audit.spec.cjs','tests/redo/r08/worker-audit.spec.cjs'],priorValidators=priorFiles.map(file=>{const base=normalize(show(round8,file)),now=current(file),testCount=(now.match(/\btest\(/g)||[]).length,baselineTestCount=(base.match(/\btest\(/g)||[]).length,changed=base!==now;return{file,baselineSha:hash(base),currentSha:hash(now),baselineTestCount,currentTestCount:testCount,assertionDeleted:testCount<baselineTestCount,expectedValueChanged:changed,pass:!changed&&testCount>=baselineTestCount};}),r09Sources=['tests/redo/r09/integration-audit.spec.cjs','tests/redo/r09/public-audit.spec.cjs','tests/redo/r09/shared-audit.spec.cjs','tests/redo/r09/generate.cjs','tests/redo/r09/validate.cjs'].map(current).join('\n'),literalPatterns=[['pass','true'],['routeListUnchanged','true'],['screenIdsUnchanged','true'],['unhandledRejections','0'],['observerLoops','0'],['duplicateActions','0'],['specimens','true'],['keyboard','true'],['responsive','true'],['domSame','true'],['styleSame','true'],['boxSame','true'],['renderer','true'],['routeGuard','true']],hardcodedResults=literalPatterns.flatMap(([field,value])=>{const regex=new RegExp(`${field}\\s*:\\s*${value}`,'g');return[...r09Sources.matchAll(regex)].map(match=>({field,value,index:match.index}));}),invalidCountAssertions=(r09Sources.match(/count\(\)\s*>=\s*0/g)||[]).length,evidenceDirectories=stateStats.directoryEvidence,genericAssertions=stateStats.genericAssertion,integrityPass=priorValidators.every(item=>item.pass)&&hardcodedResults.length===0&&invalidCountAssertions===0&&evidenceDirectories===0&&genericAssertions===0;
write('validator-integrity-audit.json',{generatedAt,priorValidators,hardcodedResults,invalidCountAssertions,evidenceDirectories,genericAssertions,itemInternalPassRequired:true,evidenceRelevanceRequired:true,fabricatedStateDetection:true,invalidRoundPathDetection:true,independentValidation:true,pass:integrityPass});
