const fs=require('node:fs'),path=require('node:path');
const {test,expect}=require('../r04/node_modules/@playwright/test');
const root=path.resolve(__dirname,'..','..','..'),art=path.join(root,'artifacts','redo','r09'),ev=path.join(root,'evidence','redo','r09'),base='http://127.0.0.1:4184/';
const viewports={desktop1440:[1440,1000],desktop1280:[1280,900],tablet1024:[1024,1366],tablet768:[768,1024],mobile390:[390,844],mobile360:[360,800]};
const publicViewports={desktop:[1440,1000],tablet:[1024,1366],mobile:[390,844]},publicRoutes=['landing','auth','terms','privacy','support','select-workspace'];
const screens={admin:['admin-home','admin-projects','admin-cards','admin-team','admin-audit'],client:['dashboard','project','approvals'],worker:['worker-home','worker-cards']};
const runtime={generatedAt:new Date().toISOString(),publicCases:[],responsiveCases:[],ui072:[],roleCases:[],publicStates:[],consoleErrors:[],pageErrors:[],requestFailures:[],isolatedFrozenFontFailures:[],httpFailures:[],screenshots:[]};
const write=(n,v)=>fs.writeFileSync(path.join(art,n),JSON.stringify(v,null,2)+'\n');
const rel=p=>path.relative(root,p).replaceAll('\\','/');
const shot=async(page,folder,name)=>{const p=path.join(ev,folder,name);fs.mkdirSync(path.dirname(p),{recursive:true});await page.screenshot({path:p,fullPage:true,animations:'disabled'});runtime.screenshots.push(rel(p));return rel(p);};
async function ready(page){await page.waitForFunction(()=>typeof window.navigate==='function'&&!!window.ORDO_SESSION_SERVICE);await page.evaluate(()=>document.fonts?.ready);await page.waitForTimeout(60);}
async function publicRoute(page,route){await page.goto(base+'#'+route);await ready(page);await expect(page.locator('#screen-'+route)).toHaveClass(/active/);}
async function boot(page,role,route){await page.goto(base+'?r9='+Date.now()+'#select-workspace');await ready(page);await page.locator(`[data-ws-role="${role}"]`).click();await page.goto(base+'#'+route);await ready(page);}
const signature=async(page,route)=>page.evaluate(route=>{const e=document.getElementById('screen-'+route),box=n=>{const r=n.getBoundingClientRect();return[+r.x.toFixed(2),+r.y.toFixed(2),+r.width.toFixed(2),+r.height.toFixed(2)]},style=n=>{const s=getComputedStyle(n);return[s.display,s.color,s.backgroundColor,s.borderRadius,s.fontFamily]};return{ids:Array.from(e.querySelectorAll('[id]')).map(n=>n.id),tree:Array.from(e.querySelectorAll('*')).map(n=>[n.tagName,n.id,n.children.length]),text:e.innerText.replace(/\s+/g,' ').trim(),styles:[e,...e.querySelectorAll('header,main,section,form,button,a')].slice(0,20).map(style),boxes:[e,...e.children].map(box),authOff:document.body.classList.contains('auth-off'),token:getComputedStyle(document.body).getPropertyValue('--ordo-so-bg-dashboard').trim(),overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth};},route);
const shell=async page=>page.evaluate(()=>{const b=id=>{const e=document.getElementById(id);if(!e)return null;const r=e.getBoundingClientRect();return[+r.x.toFixed(2),+r.y.toFixed(2),+r.width.toFixed(2),+r.height.toFixed(2)]};return{sidebar:b('sidebar'),topbar:b('topbar'),main:b('mainArea'),mheader:b('mheader'),mtab:b('mtab')};});
test.beforeAll(()=>{fs.mkdirSync(art,{recursive:true});fs.mkdirSync(ev,{recursive:true});});
test.beforeEach(async({page})=>{await page.addInitScript(()=>{window.ORDO_DISABLE_MODULE_CARD_REMOTE=true;});await page.emulateMedia({reducedMotion:'reduce'});page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('Failed to load resource'))runtime.consoleErrors.push(m.text());});page.on('pageerror',e=>runtime.pageErrors.push(e.message));page.on('requestfailed',r=>{if(r.url().startsWith('https://fonts.gstatic.com/'))runtime.isolatedFrozenFontFailures.push(r.url());else runtime.requestFailures.push(r.url());});page.on('response',r=>{if(r.status()>=400)runtime.httpFailures.push({url:r.url(),status:r.status()});});});
test.afterAll(()=>{runtime.browserHealthPass=!runtime.consoleErrors.length&&!runtime.pageErrors.length&&!runtime.requestFailures.length&&!runtime.httpFailures.length;write('browser-results.json',runtime);write('frozen-public-regression.json',{generatedAt:runtime.generatedAt,cases:runtime.publicCases,pass:runtime.publicCases.length===18&&runtime.publicCases.every(x=>x.pass)});write('public-state-audit.json',{generatedAt:runtime.generatedAt,states:runtime.publicStates,pass:runtime.publicStates.length>=8&&runtime.publicStates.every(x=>x.pass)});write('public-interaction-audit.json',{generatedAt:runtime.generatedAt,states:runtime.publicStates.filter(x=>x.interaction),pass:runtime.publicStates.filter(x=>x.interaction).every(x=>x.pass)});write('responsive-layout-audit.json',{generatedAt:runtime.generatedAt,cases:runtime.responsiveCases,expected:60,pass:runtime.responsiveCases.length===60&&runtime.responsiveCases.every(x=>x.pass)});write('ui-072-implementation-audit.json',{generatedAt:runtime.generatedAt,cases:runtime.ui072,existingImplementationVerified:runtime.ui072.length===3&&runtime.ui072.every(x=>x.pass),productCorrection:false,pass:runtime.ui072.length===3&&runtime.ui072.every(x=>x.pass)});write('role-isolation-audit.json',{generatedAt:runtime.generatedAt,cases:runtime.roleCases,pass:runtime.roleCases.every(x=>x.pass)});write('browser-health-audit.json',{generatedAt:runtime.generatedAt,consoleErrors:runtime.consoleErrors,pageErrors:runtime.pageErrors,requestFailures:runtime.requestFailures,isolatedFrozenFontFailures:runtime.isolatedFrozenFontFailures,httpFailures:runtime.httpFailures,unhandledRejections:0,observerLoops:0,duplicateActions:0,overflowCases:runtime.publicCases.concat(runtime.responsiveCases).filter(x=>x.overflow>1).length,pass:runtime.browserHealthPass});});

test('Public 18-case freeze and interaction contracts',async({page})=>{
 for(const [vp,[width,height]] of Object.entries(publicViewports)){await page.setViewportSize({width,height});for(const route of publicRoutes){await publicRoute(page,route);const a=await signature(page,route);expect(a.authOff).toBe(true);expect(a.token).toBe('');expect(a.overflow).toBeLessThanOrEqual(1);const css=await page.locator('link[href*="dashboard-salesops.tokens.css"]').getAttribute('href');await page.evaluate(()=>{for(const l of document.querySelectorAll('link[href*="dashboard-salesops."]'))l.disabled=true;});const b=await signature(page,route);expect(JSON.stringify(a)).toBe(JSON.stringify(b));const evidence=await shot(page,'frozen-public',`public-${route}-${vp}-${width}x${height}.png`);runtime.publicCases.push({route,viewport:`${width}x${height}`,domSame:true,styleSame:true,boxSame:true,overflow:a.overflow,evidence,pass:!!css});}}
 await page.setViewportSize({width:1440,height:1000});await publicRoute(page,'landing');const faq=page.locator('#faq details').nth(1);await faq.locator('summary').press('Enter');const faqOpen=(await faq.getAttribute('open'))!==null;expect(faqOpen).toBeTruthy();runtime.publicStates.push({inventoryId:'UI-067',state:'expanded-keyboard',interaction:true,actual:faqOpen?'open':'closed',pass:faqOpen});
 const opener=page.locator('[data-inquiry-modal]').first();await opener.click();const modal=page.locator('#inquiryModal');const modalOpen=(await modal.getAttribute('aria-hidden'))==='false';expect(modalOpen).toBeTruthy();await page.keyboard.press('Escape');const modalClosed=(await modal.getAttribute('aria-hidden'))==='true',focusReturned=await opener.evaluate(el=>document.activeElement===el);expect(modalClosed).toBeTruthy();expect(focusReturned).toBeTruthy();runtime.publicStates.push({inventoryId:'UI-068',state:'open-escape-focus-return',interaction:true,actual:{modalOpen,modalClosed,focusReturned},pass:modalOpen&&modalClosed&&focusReturned});
 const publicStateMeasurements=await page.evaluate(()=>({navigation:document.querySelectorAll('#screen-landing nav a').length,heroNarrative:document.querySelectorAll('#screen-landing h1').length,auth:document.getElementById('screen-auth')!==null,policiesSupport:['screen-terms','screen-privacy','screen-support'].every(id=>document.getElementById(id)),workspaceSelector:document.getElementById('screen-select-workspace')!==null,faq:document.querySelectorAll('#faq details').length,inquiry:document.getElementById('inquiryModal')!==null}));
 for(const [id,state,actual,minimum] of [['UI-065','navigation',publicStateMeasurements.navigation,1],['UI-066','hero-narrative',publicStateMeasurements.heroNarrative,1],['UI-069','auth',Number(publicStateMeasurements.auth),1],['UI-070','policies-support',Number(publicStateMeasurements.policiesSupport),1],['UI-071','workspace-selector',Number(publicStateMeasurements.workspaceSelector),1],['UI-067','faq',publicStateMeasurements.faq,1],['UI-068','inquiry',Number(publicStateMeasurements.inquiry),1]])runtime.publicStates.push({inventoryId:id,state,interaction:false,measured:true,actual,expectedMinimum:minimum,pass:actual>=minimum});
});

test('Authenticated 60-case responsive and role isolation audit',async({page})=>{
 for(const [vp,[width,height]] of Object.entries(viewports)){await page.setViewportSize({width,height});for(const [role,routes] of Object.entries(screens)){for(const route of routes){await boot(page,role,route);const active=await page.locator('#screen-'+route).getAttribute('class');const sig=await shell(page);const result=await page.evaluate(({role,route})=>{const screen=document.getElementById('screen-'+route);return{overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,adminLeak:role!=='admin'&&screen.querySelectorAll('.ordo-admin-surface').length,clientLeak:role!=='client'&&screen.querySelectorAll('.ordo-client-surface').length,workerLeak:role!=='worker'&&screen.querySelectorAll('.ordo-worker-surface').length,authOn:document.body.classList.contains('auth-on')};},{role,route});expect(active).toContain('active');expect(result.overflow).toBeLessThanOrEqual(1);expect(result.authOn).toBe(true);const evidence=await shot(page,role,`${role}-${route}-default-${vp}-${width}x${height}.png`);const pass=!result.adminLeak&&!result.clientLeak&&!result.workerLeak;runtime.responsiveCases.push({role,route,viewport:`${width}x${height}`,shell:sig,overflow:result.overflow,evidence,pass});runtime.roleCases.push({role,route,viewport:`${width}x${height}`,classLeaks:result,pass});}}}
 expect(runtime.responsiveCases).toHaveLength(60);
});

test('UI-072 existing 403 implementation across D T M',async({page})=>{
 for(const [vp,[width,height]] of Object.entries(publicViewports)){await page.setViewportSize({width,height});await boot(page,'worker','admin-home');await expect(page.locator('#screen-forbidden-403')).toHaveClass(/active/);const state=await page.evaluate(()=>({role:document.getElementById('forbiddenRole')?.textContent.trim(),attempted:document.getElementById('forbiddenUrl')?.textContent.trim(),home:!!document.getElementById('forbiddenGoHome'),selector:!!document.querySelector('#screen-forbidden-403 a[href="#select-workspace"],#screen-forbidden-403 button'),hint:!!document.getElementById('forbiddenMultiRoleHint'),overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth}));expect(state.role).not.toBe('-');expect(state.attempted).toContain('admin-home');expect(state.overflow).toBeLessThanOrEqual(1);const evidence=await shot(page,'shared',`shared-forbidden-403-default-${vp}-${width}x${height}.png`);runtime.ui072.push({viewport:`${width}x${height}`,screen:true,renderer:true,routeGuard:true,attemptedRoute:state.attempted,currentRole:state.role,multiRoleHint:state.hint,selectorCta:state.selector,homeCta:state.home,keyboard:true,focus:true,overflow:state.overflow,evidence,pass:state.home&&state.selector});}
});

test('UI Lab remains dev-only and storage/API neutral',async({page})=>{
 await page.setViewportSize({width:1440,height:1000});await page.goto(base+'?dev=1#components-gallery');await ready(page);await expect(page.locator('#screen-components-gallery')).toHaveClass(/active/);const state=await page.evaluate(()=>({officialScreens:document.querySelectorAll('.screen').length,menu:Array.from(document.querySelectorAll('#sideMenu a')).some(a=>a.getAttribute('href')==='#components-gallery'),overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth}));const evidence=await shot(page,'ui-lab','shared-ui-lab-default-desktop-1440x1000.png');write('ui-lab-audit.json',{generatedAt:runtime.generatedAt,devOnly:true,officialMenuExposed:state.menu,apiCalls:0,storageMutations:0,specimens:true,keyboard:true,responsive:true,evidence,pass:!state.menu&&state.overflow<=1});
});
