const {test,expect}=require('../r04/node_modules/@playwright/test');
const {round8Base,viewports,write,shot,bootAt,boot}=require('./audit-helpers.cjs');
const screens={admin:['admin-home','admin-projects','admin-cards','admin-team','admin-audit'],client:['dashboard','project','approvals'],worker:['worker-home','worker-cards']};
const runtime={generatedAt:new Date().toISOString(),responsiveCases:[],roleCases:[],consoleErrors:[],pageErrors:[],requestFailures:[],round8BaselineRequestFailures:[],httpFailures:[],round8BaselineHttpFailures:[],measuringRound8:false};
const shell=async page=>page.evaluate(()=>{const b=id=>{const e=document.getElementById(id);if(!e)return null;const r=e.getBoundingClientRect();return[+r.x.toFixed(2),+r.y.toFixed(2),+r.width.toFixed(2),+r.height.toFixed(2)]};return{sidebar:b('sidebar'),topbar:b('topbar'),main:b('mainArea'),mheader:b('mheader'),mtab:b('mtab')};});
test.beforeEach(async({page})=>{await page.addInitScript(()=>{window.ORDO_DISABLE_MODULE_CARD_REMOTE=true;window.__r9Unhandled=[];addEventListener('unhandledrejection',event=>window.__r9Unhandled.push(String(event.reason?.message||event.reason||'unknown')));});await page.emulateMedia({reducedMotion:'reduce'});page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('Failed to load resource'))runtime.consoleErrors.push(m.text());});page.on('pageerror',e=>runtime.pageErrors.push(e.message));page.on('requestfailed',r=>(runtime.measuringRound8?runtime.round8BaselineRequestFailures:runtime.requestFailures).push(r.url()));page.on('response',r=>{if(r.status()>=400)(runtime.measuringRound8?runtime.round8BaselineHttpFailures:runtime.httpFailures).push({url:r.url(),status:r.status()});});});
test.afterAll(()=>{const responsivePass=runtime.responsiveCases.length===60&&runtime.responsiveCases.every(x=>x.pass),rolePass=runtime.roleCases.length===60&&runtime.roleCases.every(x=>x.pass),baselineUrls=new Set(runtime.round8BaselineRequestFailures.map(url=>url.replace(round8Base,'http://127.0.0.1:4184/'))),newRequestFailures=runtime.requestFailures.filter(url=>!baselineUrls.has(url)),baselineHttp=new Set(runtime.round8BaselineHttpFailures.map(item=>`${item.url.replace(round8Base,'http://127.0.0.1:4184/')}|${item.status}`)),newHttpFailures=runtime.httpFailures.filter(item=>!baselineHttp.has(`${item.url}|${item.status}`));write('responsive-layout-audit.json',{generatedAt:runtime.generatedAt,cases:runtime.responsiveCases,expected:60,pass:responsivePass});write('role-isolation-audit.json',{generatedAt:runtime.generatedAt,cases:runtime.roleCases,classLeakCount:runtime.roleCases.filter(x=>x.classLeakCount>0).length,tokenLeakCount:runtime.roleCases.filter(x=>x.tokenLeakCount>0).length,pass:rolePass});write('authenticated-health.json',{generatedAt:runtime.generatedAt,round8BaselineRef:'2911cc85922bf32f31d051216aca9f29ed906564',consoleErrors:runtime.consoleErrors,pageErrors:runtime.pageErrors,round8BaselineRequestFailures:runtime.round8BaselineRequestFailures,requestFailures:runtime.requestFailures,newRequestFailures,round8BaselineHttpFailures:runtime.round8BaselineHttpFailures,httpFailures:runtime.httpFailures,newHttpFailures,pass:[runtime.consoleErrors,runtime.pageErrors,newRequestFailures,newHttpFailures].every(x=>x.length===0)});});

test('Authenticated 60-case responsive and role isolation audit',async({page})=>{
 runtime.measuringRound8=true;await page.setViewportSize({width:1440,height:1000});await bootAt(page,round8Base,'admin','admin-home');await page.goto(round8Base+'?dev=1#components-gallery');await page.waitForFunction(()=>document.getElementById('screen-components-gallery')?.classList.contains('active'));await page.evaluate(()=>document.fonts?.ready);await page.waitForTimeout(150);runtime.measuringRound8=false;
 for(const [viewport,[width,height]] of Object.entries(viewports)){await page.setViewportSize({width,height});for(const [role,routes] of Object.entries(screens)){for(const route of routes){await boot(page,role,route);const result=await page.evaluate(({role,route})=>{const screen=document.getElementById('screen-'+route),styles=getComputedStyle(document.body);const classLeakCount=(role!=='admin'?screen.querySelectorAll('.ordo-admin-surface').length:0)+(role!=='client'?screen.querySelectorAll('.ordo-client-surface').length:0)+(role!=='worker'?screen.querySelectorAll('.ordo-worker-surface').length:0),tokenLeakCount=(role!=='admin'&&styles.getPropertyValue('--ordo-admin-accent').trim()?1:0)+(role!=='client'&&styles.getPropertyValue('--ordo-client-accent').trim()?1:0)+(role!=='worker'&&styles.getPropertyValue('--ordo-worker-accent').trim()?1:0);return{active:screen.classList.contains('active'),overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,classLeakCount,tokenLeakCount,authenticated:document.body.classList.contains('auth-on'),currentRole:window.ORDO_ROLE,sessionRole:localStorage.getItem('ordo_active_role')};},{role,route});const geometry=await shell(page),evidence=await shot(page,role,`${role}-${route}-default-${viewport}-${width}x${height}.png`),pass=result.active&&result.overflow<=1&&result.classLeakCount===0&&result.tokenLeakCount===0&&result.authenticated&&result.currentRole===role&&result.sessionRole===role;runtime.responsiveCases.push({role,route,viewport:`${width}x${height}`,shell:geometry,overflow:result.overflow,evidence,pass});runtime.roleCases.push({role,route,viewport:`${width}x${height}`,classLeakCount:result.classLeakCount,tokenLeakCount:result.tokenLeakCount,routeGuard:result.active,session:result.currentRole===role&&result.sessionRole===role,pass});expect(pass).toBeTruthy();}}}
 expect(runtime.responsiveCases).toHaveLength(60);
});
