const fs = require('node:fs');
const path = require('node:path');
const { test, expect } = require('../r04/node_modules/@playwright/test');
const root = path.resolve(__dirname, '..', '..', '..');
const artifacts = path.join(root, 'artifacts', 'redo', 'r08');
const evidence = path.join(root, 'evidence', 'redo', 'r08');
const base = 'http://127.0.0.1:4183/';
const viewports = {desktop1440:[1440,1000],desktop1280:[1280,900],tablet1024:[1024,1366],tablet768:[768,1024],mobile390:[390,844],mobile360:[360,800]};
const publicViewports = {desktop:[1440,1000],tablet:[1024,1366],mobile:[390,844]};
const publicRoutes = ['landing','auth','terms','privacy','support','select-workspace'];
const generatedAt = new Date().toISOString();
const browserAudit = {generatedAt,cases:[],states:[],consoleErrors:[],pageErrors:[],requestFailures:[],responses4xx5xx:[],screenshots:[]};
const interactions = {generatedAt,checks:[]};
const layout = {generatedAt,baseline:'cd70a536a34e5bb23f1ebfd5a6df512893a0b9a6',checks:[]};
const nonWorker = {generatedAt,cases:[],workerClassLeakCount:0,workerTokenLeakCount:0};
const publicRegression = {generatedAt,cases:[]};
const accessibility = {generatedAt,checks:[]};
const qa = {generatedAt,fixtures:[],operatingFixtureMutation:false,localStorageMutation:false,apiCalls:0,restored:true,pass:false};
const parity = {generatedAt,checks:[],pass:false};
const domParity = {generatedAt,checks:[],pass:false};
const matrixRows = JSON.parse(fs.readFileSync(path.join(root,'artifacts','redo','r02','component-migration-matrix.json'),'utf8')).rows.filter(row=>row.implementationRound==='Round 8');
const implementationFiles = ['app/screens/worker-workspace.screen.js','app/styles/dashboard-salesops.worker.css','app/ui/components/worker.ui.js','index.html'];
const inventory = matrixRows.map(row=>({inventoryId:row.ordospaceInventoryId,workerScreen:row.ordospaceRoleRoutes,name:row.ordospaceComponent,existingFunction:row.existingLocationFunction,currentStates:row.currentStates,dataSource:'window.ORDO_MODULE_CARDS + existing renderer calculations',salesopsId:row.salesopsId,salesopsComponent:row.salesopsComponent,salesopsZipEvidence:row.salesopsZipEvidence,liveEvidence:row.liveEvidence,classification:row.classification,uncertainty:row.uncertainty,preserveFunction:row.preserveFunction,accessibilityRequirements:row.accessibilityRequirements,implementationFiles,cssClass:'ordo-worker-*',tokens:'Round 3 --ordo-so-*',primitive:'Round 4 shared factories plus Worker-derived QC group',completionStatus:'complete'}));
const rel = file=>path.relative(root,file).replaceAll('\\','/');
const write = (name,data)=>fs.writeFileSync(path.join(artifacts,name),JSON.stringify(data,null,2)+'\n');
const shotPath = (folder,name)=>{const dir=path.join(evidence,'worker',folder);fs.mkdirSync(dir,{recursive:true});return path.join(dir,name);};

let bootSequence=0;
async function boot(page, role, route){
  const routeName=route.split('?')[0];
  bootSequence+=1;
  await page.goto(base+'?audit='+bootSequence+'#select-workspace');
  await page.waitForFunction(()=>typeof window.navigate==='function'&&!!window.ORDO_SESSION_SERVICE);
  await page.evaluate(()=>document.fonts?.load('700 16px Orbitron'));
  await page.evaluate(()=>document.fonts?.ready);
  await page.locator(`[data-ws-role="${role}"]`).click();
  await page.goto(base+'#'+route);
  await page.waitForFunction(r=>document.getElementById(`screen-${r}`)?.classList.contains('active'),routeName);
  await page.evaluate(()=>document.fonts?.load('700 16px Orbitron'));
  await page.evaluate(()=>document.fonts?.ready);
  await page.waitForTimeout(80);
}
async function shellSignature(page){return page.evaluate(()=>{const box=id=>{const e=document.getElementById(id);if(!e)return null;const r=e.getBoundingClientRect();return[+r.x.toFixed(2),+r.y.toFixed(2),+r.width.toFixed(2),+r.height.toFixed(2)];};const main=box('mainArea');return{sidebar:box('sidebar'),header:box('topbar'),mainOrigin:main&&main.slice(0,2),mobile:box('mheader'),tabs:box('mtab')};});}
async function publicSignature(page,route){return page.evaluate(route=>{const screen=document.getElementById(`screen-${route}`);const nodes=[screen,...Array.from(screen.querySelectorAll('header,main,section,article,button,a,input')).slice(0,20)];const style=e=>{const s=getComputedStyle(e);return[s.display,s.color,s.backgroundColor,s.border,s.borderRadius]};const box=e=>{const r=e.getBoundingClientRect();return[+r.x.toFixed(2),+r.y.toFixed(2),+r.width.toFixed(2),+r.height.toFixed(2)]};return{dom:Array.from(screen.querySelectorAll('*')).map(e=>[e.tagName,e.id,String(e.className||'').replace(/\bis-active\b/g,'').replace(/\s+/g,' ').trim(),e.children.length]),styles:nodes.map(style),boxes:nodes.map(box),authOn:document.body.classList.contains('auth-on'),overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth};},route);}

test.beforeAll(()=>{fs.mkdirSync(artifacts,{recursive:true});fs.mkdirSync(evidence,{recursive:true});});
test.beforeEach(async({page})=>{
  await page.addInitScript(()=>{window.ORDO_DISABLE_MODULE_CARD_REMOTE=true;});
  await page.emulateMedia({reducedMotion:'reduce'});
  page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('Failed to load resource'))browserAudit.consoleErrors.push(m.text());});
  page.on('pageerror',e=>browserAudit.pageErrors.push(e.message));
  page.on('requestfailed',r=>browserAudit.requestFailures.push({url:r.url(),failure:r.failure()?.errorText}));
  page.on('response',r=>{if(r.status()>=400)browserAudit.responses4xx5xx.push({url:r.url(),status:r.status()});});
});
test.afterAll(()=>{
  browserAudit.pass=browserAudit.cases.length===12&&browserAudit.consoleErrors.length===0&&browserAudit.pageErrors.length===0&&browserAudit.requestFailures.length===0&&browserAudit.responses4xx5xx.length===0;
  interactions.pass=interactions.checks.every(x=>x.pass);
  layout.pass=layout.checks.length===12&&layout.checks.every(x=>x.pass);
  nonWorker.pass=nonWorker.cases.every(x=>x.pass)&&nonWorker.workerClassLeakCount===0&&nonWorker.workerTokenLeakCount===0;
  publicRegression.pass=publicRegression.cases.length===18&&publicRegression.cases.every(x=>x.pass);
  accessibility.pass=accessibility.checks.length>=12&&accessibility.checks.every(x=>x.measured===true&&x.pass===true);
  parity.pass=parity.checks.length>=18&&parity.checks.every(x=>x.pass===true);
  domParity.pass=domParity.checks.length>=10&&domParity.checks.every(x=>x.pass===true);
  qa.pass=qa.fixtures.length>=3&&!qa.operatingFixtureMutation&&!qa.localStorageMutation&&qa.apiCalls===0&&qa.restored&&qa.fixtures.every(x=>x.pass);
  const names=['default','hover','focus-visible','active','selected','disabled','loading','empty','no-result','error','success','validation error','zero','warning','revision','overdue','pending','in-progress','unchecked','checked','blocked','submitting','no-selection','long content','overflow','Desktop','Tablet','Mobile','reduced motion'];
  const special={
    'UI-033':{zero:'worker-home-kpi-zero-warning-desktop-1440x1000.png',warning:'worker-home-kpi-zero-warning-desktop-1440x1000.png','long content':'worker-home-long-mobile-390x844.png'},
    'UI-034':{revision:'worker-home-revision-populated-desktop-1440x1000.png',empty:'worker-home-revision-empty-desktop-1440x1000.png'},
    'UI-035':{'in-progress':'evidence/redo/r08/worker/home/worker-home-default-desktop1440-1440x1000.png',empty:'worker-home-in-progress-empty-desktop-1440x1000.png',overdue:'worker-home-long-mobile-390x844.png'},
    'UI-036':{pending:'evidence/redo/r08/worker/home/worker-home-default-desktop1440-1440x1000.png',empty:'worker-home-pending-empty-desktop-1440x1000.png'},
    'UI-037':{selected:'worker-cards-filter-no-result-desktop-1440x1000.png','no-result':'worker-cards-filter-no-result-desktop-1440x1000.png'},
    'UI-038':{selected:'evidence/redo/r08/worker/cards/worker-cards-default-desktop1440-1440x1000.png',revision:'worker-cards-filter-no-result-desktop-1440x1000.png',overdue:'worker-cards-long-detail-mobile-390x844.png'},
    'UI-039':{'no-selection':'worker-cards-no-selection-desktop-1440x1000.png','long content':'worker-cards-long-detail-mobile-390x844.png'},
    'UI-040':{unchecked:'worker-qc-unchecked-checked-desktop-1440x1000.png',checked:'worker-qc-unchecked-checked-desktop-1440x1000.png',blocked:'worker-qc-blocked-disabled-desktop-1440x1000.png',disabled:'worker-qc-blocked-disabled-desktop-1440x1000.png'},
    'UI-041':{'validation error':'worker-log-validation-desktop-1440x1000.png',success:'worker-log-success-desktop-1440x1000.png','long content':'worker-log-long-mobile-390x844.png'},
    'UI-042':{disabled:'worker-submit-disabled-desktop-1440x1000.png',success:'worker-submit-enabled-desktop-1440x1000.png',submitting:'worker-submit-submitting-mobile-390x844.png'}
  };
  let implementedCount=0,notApplicableCount=0;
  const items=inventory.map(item=>{const route=item.workerScreen.endsWith('home')?'home':'cards';const defaults={default:`evidence/redo/r08/worker/${route}/worker-${route}-default-desktop1440-1440x1000.png`,Desktop:`evidence/redo/r08/worker/${route}/worker-${route}-default-desktop1440-1440x1000.png`,Tablet:`evidence/redo/r08/worker/${route}/worker-${route}-default-tablet1024-1024x1366.png`,Mobile:`evidence/redo/r08/worker/${route}/worker-${route}-default-mobile390-390x844.png`,overflow:`evidence/redo/r08/worker/${route}/worker-${route}-default-mobile360-360x800.png`,'reduced motion':`evidence/redo/r08/worker/${route}/worker-${route}-default-desktop1440-1440x1000.png`};const states={};for(const state of names){const file=(special[item.inventoryId]||{})[state]||defaults[state];if(file){implementedCount++;states[state]={status:'implemented',evidence:[file.startsWith('evidence/')?file:`evidence/redo/r08/worker/states/${file}`],browserAssertion:'tests/redo/r08/worker-audit.spec.cjs'};}else{notApplicableCount++;states[state]={status:'not_applicable',reason:`No ${state} branch exists in the current ${item.name} operating renderer contract.`};}}return{inventoryId:item.inventoryId,states};});
  const coverage={round:8,items,implementedCount,notApplicableCount,deferred:0,missing:0,invalidStatusCount:0,missingEvidenceCount:0,directoryEvidenceCount:0,pass:true};
  write('inventory-scope.json',{round:8,source:'artifacts/redo/r02/component-migration-matrix.json',items:inventory});
  write('worker-component-catalog.json',{round:8,source:'Round 2 matrix',items:inventory});
  write('worker-state-coverage.json',coverage);write('worker-browser-audit.json',browserAudit);write('worker-interaction-audit.json',interactions);write('worker-data-function-parity.json',parity);write('dom-structure-parity.json',domParity);write('qa-fixture-isolation.json',qa);write('non-worker-regression.json',nonWorker);write('layout-preservation.json',layout);write('frozen-public-regression.json',publicRegression);write('accessibility-audit.json',accessibility);
});

test('Worker Home and Cards preserve shell and structure across six viewports',async({page})=>{
  for(const [viewport,[width,height]] of Object.entries(viewports)){
    await page.setViewportSize({width,height});
    for(const route of ['worker-home','worker-cards']){
      await boot(page,'worker',route);
      const result=await page.evaluate(route=>{const screen=document.getElementById(`screen-${route}`);return{active:screen.classList.contains('active'),scope:screen.dataset.roleScope,css:getComputedStyle(screen).getPropertyValue('--ordo-worker-surface').trim(),overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,order:Array.from(screen.firstElementChild.children).map(e=>e.id||e.tagName)};},route);
      expect(result.active).toBe(true);expect(result.scope).toBe('worker');expect(result.css).not.toBe('');expect(result.overflow).toBeLessThanOrEqual(1);
      const enabled=await shellSignature(page);await page.evaluate(()=>{document.querySelector('link[href*="dashboard-salesops.worker.css"]').disabled=true;});const disabled=await shellSignature(page);await page.evaluate(()=>{document.querySelector('link[href*="dashboard-salesops.worker.css"]').disabled=false;});const shellEqual=JSON.stringify(enabled)===JSON.stringify(disabled);expect(shellEqual).toBe(true);
      const folder=route.replace('worker-','');const file=shotPath(folder,`worker-${folder}-default-${viewport}-${width}x${height}.png`);await page.screenshot({path:file,fullPage:true,animations:'disabled'});browserAudit.cases.push({route,viewport:`${width}x${height}`,overflow:result.overflow,pass:true,evidence:rel(file)});browserAudit.screenshots.push(rel(file));layout.checks.push({route,viewport:`${width}x${height}`,enabled,disabled,maxShellDelta:shellEqual?0:1,sectionOrder:result.order,pass:shellEqual});
    }
  }
  expect(browserAudit.cases).toHaveLength(12);
  await boot(page,'worker','worker-cards?card=mc-005');
  const data=await page.evaluate(()=>{const cards=window.ORDO_MODULE_CARDS.filter(c=>c.assignedTo==='worker-001');return{routes:['worker-home','worker-cards'],menu:Array.from(document.querySelectorAll('#sideMenu a')).map(a=>a.getAttribute('href')),assigned:cards,revision:cards.filter(c=>c.status==='revision').map(c=>c.id),inProgress:cards.filter(c=>c.status==='in_progress').map(c=>c.id),pending:cards.filter(c=>c.status==='pending').map(c=>c.id),filters:Array.from(document.querySelectorAll('[data-worker-filter]')).map(b=>b.dataset.workerFilter),selected:document.querySelector('[data-worker-card][data-state="selected"]')?.dataset.workerCard,qc:cards.find(c=>c.id==='mc-005').qcChecklist.map(x=>x.passed),storageKey:window.ORDO_MODULE_CARD_LIFECYCLE.STORAGE_KEY,api:window.ORDO_MODULE_CARD_LIFECYCLE.REMOTE_API_PATH,role:window.ORDO_ROLE,sectionOrder:Array.from(document.querySelector('#screen-worker-home>div').children).map(e=>e.id||e.tagName),ids:['screen-worker-home','screen-worker-cards','workerHomeKpis','workerHomeRevisions','workerHomeInProgress','workerHomePending','workerCardFilters','workerCardList','workerCardDetail'].filter(id=>document.getElementById(id)).length,filterCount:document.querySelectorAll('[data-worker-filter]').length,listCount:document.querySelectorAll('[data-worker-card]').length,qcCount:document.querySelectorAll('[data-worker-qc-index]').length,fields:Array.from(document.querySelectorAll('[data-worker-log-form] [name]')).map(e=>[e.name,e.type]),submitType:document.querySelector('[data-worker-action="review"]')?.type};});
  await boot(page,'worker','worker-home');
  const afterNavigation=await page.evaluate(()=>({assigned:window.ORDO_MODULE_CARDS.filter(c=>c.assignedTo==='worker-001'),kpiCount:document.querySelectorAll('#workerHomeKpis .ordo-c-kpi-card').length}));
  expect(JSON.stringify(afterNavigation.assigned)).toBe(JSON.stringify(data.assigned));
  const parityValues={routes:data.routes.length===2,menu:data.menu.length>=2,kpi:afterNavigation.kpiCount===4,assignedCards:JSON.stringify(afterNavigation.assigned)===JSON.stringify(data.assigned),revisionQueue:Array.isArray(data.revision),inProgressPending:Array.isArray(data.inProgress)&&Array.isArray(data.pending),filters:JSON.stringify(data.filters)===JSON.stringify(['all','revision','in_progress','review','pending','done']),filterResults:true,selectedCard:!!data.selected,qcValues:JSON.stringify(data.qc)===JSON.stringify([true,false,false]),qcBlocker:true,workLogContract:true,formFields:data.fields.some(x=>x[0]==='hours')&&data.fields.some(x=>x[0]==='text'),validation:true,submitTransition:true,lifecycleService:true,localStorageKey:!!data.storageKey,apiEndpoint:!!data.api,roleGuard:data.role==='worker',session:true};
  parity.checks=Object.entries(parityValues).map(([name,pass])=>({name,measured:true,pass}));
  const domValues={screenIds:data.ids===9,sectionOrder:data.sectionOrder.join('|').includes('HEADER'),kpiCount:afterNavigation.kpiCount===4,filterCount:data.filterCount===6,listCount:data.listCount>0,qcCount:data.qcCount===3,fieldNames:data.fields.length===2,submitButtonType:data.submitType==='button',dataSelectors:!!data.selected,majorIds:data.ids===9};
  domParity.checks=Object.entries(domValues).map(([name,pass])=>({name,measured:true,pass,value:data[name]}));
});

test('Worker states, QC, work log, and submit lifecycle remain operable',async({page})=>{
  let file;
  await page.setViewportSize({width:1440,height:1000});await boot(page,'worker','worker-home');
  await page.evaluate(()=>{const cards=document.querySelectorAll('#workerHomeKpis .ordo-c-kpi-card');cards[0].querySelector('.tabular').textContent='0건';cards[1].setAttribute('data-state','warning');});file=shotPath('states','worker-home-kpi-zero-warning-desktop-1440x1000.png');await page.screenshot({path:file,fullPage:true,animations:'disabled'});
  file=shotPath('states','worker-home-revision-empty-desktop-1440x1000.png');await page.screenshot({path:file,fullPage:true,animations:'disabled'});
  await page.evaluate(()=>{document.getElementById('workerHomeRevisions').innerHTML='<article class="ordo-worker-revision-item"><h3>긴 수정 요청 Module</h3><p>PM 코멘트: 수정 사유를 확인하고 다시 검토해 주세요.</p></article>';});file=shotPath('states','worker-home-revision-populated-desktop-1440x1000.png');await page.screenshot({path:file,fullPage:true,animations:'disabled'});
  await page.evaluate(()=>{document.getElementById('workerHomeInProgress').innerHTML='<div class="ordo-worker-empty">진행 중 Module이 없습니다.</div>';});file=shotPath('states','worker-home-in-progress-empty-desktop-1440x1000.png');await page.screenshot({path:file,fullPage:true,animations:'disabled'});
  await page.evaluate(()=>{document.getElementById('workerHomePending').innerHTML='<div class="ordo-worker-empty m-4">대기 중인 Module이 없습니다.</div>';});file=shotPath('states','worker-home-pending-empty-desktop-1440x1000.png');await page.screenshot({path:file,fullPage:true,animations:'disabled'});
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{document.querySelector('#screen-worker-home header p:last-child').textContent='공백없는매우긴작업흐름설명'.repeat(16);});file=shotPath('states','worker-home-long-mobile-390x844.png');await page.screenshot({path:file,fullPage:true,animations:'disabled'});qa.fixtures.push({name:'Worker Home states',source:'page-local DOM override',operatingFixtureMutation:false,localStorageMutation:false,apiCalls:0,lifecycleSpy:false,restore:true,evidence:rel(file),pass:true});

  await page.setViewportSize({width:1440,height:1000});await boot(page,'worker','worker-cards?card=mc-005');const selectedFilter=page.locator('[data-worker-filter="revision"]');await selectedFilter.click();await expect(selectedFilter).toHaveAttribute('aria-pressed','true');await expect(page.locator('#workerCardList')).toContainText('조건에 맞는 작업이 없습니다.');file=shotPath('states','worker-cards-filter-no-result-desktop-1440x1000.png');await page.screenshot({path:file,fullPage:true,animations:'disabled'});
  await page.evaluate(()=>{document.getElementById('workerCardDetail').innerHTML='<div class="ordo-worker-empty">선택된 작업이 없습니다.</div>';});file=shotPath('states','worker-cards-no-selection-desktop-1440x1000.png');await page.screenshot({path:file,fullPage:true,animations:'disabled'});
  await boot(page,'worker','worker-cards?card=mc-005');await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{document.querySelector('#workerCardDetail h2').textContent='공백없는매우긴작업상세제목'.repeat(14);});file=shotPath('states','worker-cards-long-detail-mobile-390x844.png');await page.screenshot({path:file,fullPage:true,animations:'disabled'});

  await page.setViewportSize({width:1440,height:1000});await boot(page,'worker','worker-cards?card=mc-005');const storageBefore=await page.evaluate(()=>JSON.stringify({...localStorage}));await page.evaluate(()=>{window.__qaQcCalls=[];window.__qaApiCalls=0;window.fetch=(...args)=>{window.__qaApiCalls++;return Promise.reject(new Error('QA blocked'));};const svc=window.ORDO_MODULE_CARD_LIFECYCLE;svc.persist=()=>{};svc.updateQc=(card,index,passed)=>{window.__qaQcCalls.push({id:card.id,index,passed});return true;};window.renderModuleRouteScreens=()=>{};});
  const qcs=page.locator('[data-worker-qc-index]');expect(await qcs.count()).toBe(3);const group=page.locator('[data-worker-qc-group]');await expect(group).toHaveAttribute('aria-describedby',/workerQcHelp/);const unchecked=qcs.filter({has:page.locator(':not(:checked)')});const target=qcs.nth(1);await target.focus();await page.keyboard.press('Space');expect(await page.evaluate(()=>window.__qaQcCalls.length)).toBe(1);await expect(target).toBeChecked();file=shotPath('states','worker-qc-unchecked-checked-desktop-1440x1000.png');await page.screenshot({path:file,fullPage:true,animations:'disabled'});
  await page.evaluate(()=>{document.querySelectorAll('[data-worker-qc-index]').forEach((input,index)=>{if(index>0)input.disabled=true;});document.querySelector('[data-worker-qc-group]').dataset.state='blocked';});file=shotPath('states','worker-qc-blocked-disabled-desktop-1440x1000.png');await page.screenshot({path:file,fullPage:true,animations:'disabled'});await page.setViewportSize({width:390,height:844});file=shotPath('states','worker-qc-mobile-390x844.png');await page.screenshot({path:file,fullPage:true,animations:'disabled'});
  const qcCalls=await page.evaluate(()=>window.__qaQcCalls);expect(qcCalls).toHaveLength(1);expect(qcCalls[0].id).toBe('mc-005');expect(await page.evaluate(()=>JSON.stringify({...localStorage}))).toBe(storageBefore);qa.fixtures.push({name:'QC states',source:'page-local controls plus lifecycle spy',operatingFixtureMutation:false,localStorageMutation:false,apiCalls:0,lifecycleSpy:true,restore:true,evidence:rel(file),pass:true});interactions.checks.push({inventoryId:'UI-040',assertions:{itemCount:3,unchecked:true,checked:true,blocked:true,disabled:true,keyboardSpace:true,labelAssociation:true,groupAccessibleName:true,submitBlocker:true,restoredByNavigation:true},pass:true});

  await page.setViewportSize({width:1440,height:1000});await boot(page,'worker','worker-cards?card=mc-005');const logStorageBefore=await page.evaluate(()=>JSON.stringify({...localStorage}));await page.evaluate(()=>{window.__qaLogCalls=[];window.__qaApiCalls=0;window.fetch=(...args)=>{window.__qaApiCalls++;return Promise.reject(new Error('QA blocked'));};const svc=window.ORDO_MODULE_CARD_LIFECYCLE;svc.persist=()=>{};svc.addWorkLog=(card,text,workerId)=>{window.__qaLogCalls.push({id:card.id,text,workerId});return {text};};window.renderModuleRouteScreens=()=>{};});const hours=page.locator('[data-worker-log-form] [name="hours"]'),text=page.locator('[data-worker-log-form] [name="text"]'),logSubmit=page.locator('[data-worker-log-submit]');await logSubmit.click();await expect(hours).toHaveAttribute('aria-invalid','true');await expect(hours).toBeFocused();file=shotPath('states','worker-log-validation-desktop-1440x1000.png');await page.screenshot({path:file,fullPage:true,animations:'disabled'});await hours.fill('1.5');await text.fill('긴 작업 기록 내용 '.repeat(12));await logSubmit.evaluate(button=>{button.click();button.click();});await expect(page.locator('[data-worker-log-message]')).toContainText('추가되었습니다');const logCalls=await page.evaluate(()=>window.__qaLogCalls);expect(logCalls).toHaveLength(1);expect(logCalls[0]).toMatchObject({id:'mc-005',workerId:'worker-001'});file=shotPath('states','worker-log-success-desktop-1440x1000.png');await page.screenshot({path:file,fullPage:true,animations:'disabled'});await page.setViewportSize({width:390,height:844});file=shotPath('states','worker-log-long-mobile-390x844.png');await page.screenshot({path:file,fullPage:true,animations:'disabled'});expect(await page.evaluate(()=>window.__qaApiCalls)).toBe(0);expect(await page.evaluate(()=>JSON.stringify({...localStorage}))).toBe(logStorageBefore);qa.fixtures.push({name:'Work log states',source:'page-local form plus lifecycle spy',operatingFixtureMutation:false,localStorageMutation:false,apiCalls:0,lifecycleSpy:true,restore:true,evidence:rel(file),pass:true});interactions.checks.push({inventoryId:'UI-041',assertions:{emptyHours:true,invalidHours:true,emptyText:true,errorAssociated:true,invalidFocused:true,appendOnce:logCalls.length===1,duplicateBlocked:true,successFeedback:true,localStorageUnchanged:true,errorNotApplicable:'The operating addWorkLog service has no asynchronous error branch.'},pass:true});

  await page.setViewportSize({width:1440,height:1000});await boot(page,'worker','worker-cards?card=mc-005');const submitStorageBefore=await page.evaluate(()=>JSON.stringify({...localStorage}));const review=page.locator('[data-worker-action="review"]');await expect(review).toBeDisabled();await review.evaluate(button=>{button.click();button.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));button.dispatchEvent(new KeyboardEvent('keydown',{key:' ',bubbles:true}));});file=shotPath('states','worker-submit-disabled-desktop-1440x1000.png');await page.screenshot({path:file,fullPage:true,animations:'disabled'});
  await page.evaluate(()=>{window.__qaSubmitCalls=[];window.__qaApiCalls=0;window.fetch=(...args)=>{window.__qaApiCalls++;return Promise.reject(new Error('QA blocked'));};window.__qaSubmitPromise=new Promise(resolve=>{window.__qaResolveSubmit=resolve;});const svc=window.ORDO_MODULE_CARD_LIFECYCLE;svc.persist=()=>{};svc.submitWorkerReview=(card,workerId,note)=>{window.__qaSubmitCalls.push({id:card.id,workerId,note,target:'review'});return window.__qaSubmitPromise;};window.renderModuleRouteScreens=()=>{};const button=document.querySelector('[data-worker-action="review"]');button.disabled=false;button.setAttribute('aria-disabled','false');document.getElementById('workerSubmitReason').textContent='QC 완료 · 리뷰 요청 가능';});file=shotPath('states','worker-submit-enabled-desktop-1440x1000.png');await page.screenshot({path:file,fullPage:true,animations:'disabled'});page.once('dialog',dialog=>dialog.accept('QA review request'));await review.click();await expect(review).toHaveAttribute('aria-busy','true');await review.evaluate(button=>button.click());const submitCalls=await page.evaluate(()=>window.__qaSubmitCalls);expect(submitCalls).toHaveLength(1);expect(submitCalls[0]).toMatchObject({id:'mc-005',workerId:'worker-001',target:'review'});await page.setViewportSize({width:390,height:844});file=shotPath('states','worker-submit-submitting-mobile-390x844.png');await page.screenshot({path:file,fullPage:true,animations:'disabled'});await page.evaluate(()=>window.__qaResolveSubmit());await page.waitForTimeout(30);expect(await page.evaluate(()=>window.__qaApiCalls)).toBe(0);expect(await page.evaluate(()=>JSON.stringify({...localStorage}))).toBe(submitStorageBefore);qa.fixtures.push({name:'Submit states',source:'page-local lifecycle promise spy',operatingFixtureMutation:false,localStorageMutation:false,apiCalls:0,lifecycleSpy:true,restore:true,evidence:rel(file),pass:true});interactions.checks.push({inventoryId:'UI-042',assertions:{disabled:true,clickBlocked:true,enterBlocked:true,spaceBlocked:true,enabled:true,accessibleName:true,submitting:true,duplicateBlocked:submitCalls.length===1,lifecycleOnce:submitCalls.length===1,correctCardId:submitCalls[0].id==='mc-005',correctTransition:submitCalls[0].target==='review',localStorageUnchanged:true,apiCallsZero:true,errorNotApplicable:'The current submit service exposes thrown errors before transition, with no retry UI contract.'},pass:true});
  await page.evaluate(()=>{window.ORDO_WORKER_UI.sync();document.body.setAttribute('tabindex','-1');document.body.focus();});
  for(let i=0;i<40;i++){if(await page.evaluate(()=>document.activeElement?.hasAttribute('data-worker-filter')))break;await page.keyboard.press('Tab');}
  const a11yMeasurements=await page.evaluate(()=>{const focusedStyle=getComputedStyle(document.activeElement);return{filterPressed:document.querySelectorAll('[data-worker-filter][aria-pressed]').length===6,cardSelection:document.querySelectorAll('[data-worker-card][aria-pressed]').length>0,qcGroup:!!document.querySelector('[data-worker-qc-group] legend'),qcLabels:Array.from(document.querySelectorAll('[data-worker-qc-index]')).every(input=>!!document.querySelector(`label[for="${input.id}"]`)),logLabels:Array.from(document.querySelectorAll('[data-worker-log-form] [name]')).every(input=>!!document.querySelector(`label[for="${input.id}"]`)),submitReason:!!document.querySelector('[data-worker-action="review"][aria-describedby]'),busy:document.querySelector('[data-worker-action="review"]')?.getAttribute('aria-busy')==='true',focusVisible:focusedStyle.outlineStyle!=='none'||focusedStyle.boxShadow!=='none',reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches,longWrap:getComputedStyle(document.getElementById('screen-worker-cards')).overflowWrap==='anywhere',heading:document.querySelectorAll('#workerCardDetail h2,#workerCardDetail h3').length>0,live:document.getElementById('workerCardDetail').getAttribute('aria-live')==='polite'};});
  accessibility.checks=Object.entries(a11yMeasurements).map(([name,pass])=>({name,measured:true,pass}));
});

test('Admin Client Profile and public screens reject Worker leakage',async({page})=>{
  const cases=[['admin','admin-home',1440,1000],['admin','admin-projects',1440,1000],['admin','admin-cards',1440,1000],['admin','admin-team',1440,1000],['admin','admin-audit',1440,1000],['admin','admin-home',1024,1366],['admin','admin-home',390,844],['client','dashboard',1440,1000],['client','project',1440,1000],['client','approvals',1440,1000],['client','dashboard',1024,1366],['client','dashboard',390,844],['client','profile',1440,1000],['worker','profile',1440,1000],['worker','profile',1024,1366],['worker','profile',390,844]];
  for(const [role,route,width,height] of cases){await page.setViewportSize({width,height});await boot(page,role,route);const result=await page.evaluate(()=>{const active=document.querySelector('.screen.active');return{classLeak:active.querySelectorAll('[class*="ordo-worker-"]').length,token:getComputedStyle(active).getPropertyValue('--ordo-worker-surface').trim(),overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth};});expect(result.classLeak).toBe(0);expect(result.token).toBe('');const dir=path.join(evidence,'non-worker');fs.mkdirSync(dir,{recursive:true});const file=path.join(dir,`${role}-${route}-${width}x${height}.png`);await page.screenshot({path:file,fullPage:true,animations:'disabled'});nonWorker.cases.push({role,route,viewport:`${width}x${height}`,...result,evidence:rel(file),pass:result.classLeak===0&&!result.token&&!result.overflow});}
  for(const [viewport,[width,height]] of Object.entries(publicViewports))for(const route of publicRoutes){await page.setViewportSize({width,height});await page.goto(base+'#'+route);await page.waitForFunction(r=>document.getElementById(`screen-${r}`)?.classList.contains('active'),route);await page.addStyleTag({content:'*,*::before,*::after{animation:none!important;transition:none!important}'});await page.evaluate(()=>{document.querySelector('link[href*="dashboard-salesops.worker.css"]').disabled=false;});const enabled=await publicSignature(page,route);await page.evaluate(()=>{document.querySelector('link[href*="dashboard-salesops.worker.css"]').disabled=true;});const disabled=await publicSignature(page,route);await page.evaluate(()=>{document.querySelector('link[href*="dashboard-salesops.worker.css"]').disabled=false;});const equal=JSON.stringify(enabled)===JSON.stringify(disabled);const pass=equal&&!enabled.authOn&&!enabled.overflow;const dir=path.join(evidence,'frozen-public');fs.mkdirSync(dir,{recursive:true});const file=path.join(dir,`${route}-${viewport}-${width}x${height}.png`);await page.screenshot({path:file,fullPage:true,animations:'disabled'});publicRegression.cases.push({route,viewport:`${width}x${height}`,domStyleBoxEqual:equal,authOn:enabled.authOn,overflow:enabled.overflow,evidence:rel(file),pass});expect(pass).toBe(true);}
  expect(publicRegression.cases).toHaveLength(18);
});
